### ISSUE TITLE
Add test to check input array does not change

### ISSUE THREAD

**Issue by crawfordsm** [astropy/ccdproc#117]
When an input array is passed to a function, it should not be modified to the function.  A test should be added to the appropriate functions that the input array does not change.

**Comment by mwcraig** [comment]
To flesh this one out a bit more, for each of the functions in `ccdproc/core.py` (or at least all of them listed in the `_all__` variable at the top of that file) there should be a test that checks whether the input array is changed.

For example, a test like that for `create_deviation` might look like this:

```python
def test_create_deviation_does_not_change_input(ccd_data):
    original = ccd_data.copy()
    ccd = create_deviation(ccd_data, gain=5 * u.electron / u.adu, readnoise=10 * u.electron)
   np.testing.assert_array_equal(original.data, ccd_data.data)
   assert original.unit == ccd_data.unit
   # maybe also check that meta is the same for both, and uncertainty.
```
