### ISSUE TITLE
Move some functions "upstream"

### ISSUE THREAD

**Issue by cdeil** [astropy/ccdproc#153]
@crawfordsm @mwcraig I just saw the `ccdproc 0.2` release announcement ... congratulations!

Looking through the list of functions in the [ccdproc API docs](http://ccdproc.readthedocs.org/en/latest/ccdproc/index.html#module-ccdproc) I think some should be moved "upstream", specifically:

* [sigma_func](http://ccdproc.readthedocs.org/en/latest/_modules/ccdproc/core.html#sigma_func) could be moved to [astropy.stats](http://astropy.readthedocs.org/en/latest/stats/index.html).
  (I've seen this factor 1.48 also show up in the [photutils docs](http://photutils.readthedocs.org/en/latest/photutils/index.html#getting-started), so it's definitely something that should be moved to the Astropy core)
* `trim_image` and `rebin` functionality be available via the [`imageutils`](https://github.com/astropy/imageutils) module soon, which is planned to become available in the core as `astropy.image`. You might still need a wrapper that can deal with `CCDData` objects, but we should keep in contact to make sure we don't duplicate basic image utils functionality.

**Comment by crawfordsm** [comment]
trim_image is mentioned in #175 and also `rebin` and `sigma_func` are now in astropy.
