### ISSUE TITLE
Combiner memory consumption

### ISSUE THREAD

**Issue by welterde** [astropy/ccdproc#176]
Stacking several 4k*4k images results in the process running out of memory quite quickly. For now I have replaced some parts locally that do the same thing line by line instead of the whole thing at once, which already reduces the memory requirements significantly, but it's still not ideal.

Are there any plans to replace the current workings of the combiner with some cython code?

**Comment by indiajoe** [comment]
The major hurdle I faced while trying to migrate from IRAF based data reduction pipelines to ccdproc was this memory issue. In Infrared observations, the number of files per objects are typically huge, and it is impossible to load all the images to memory before combining them. (for example I had to take median of ~200 frames). I don't know how IRAF does it. I guess the only way we can implement it in ccdproc is to slice the image into smaller tiles and combine one tile at a time.

**Comment by crawfordsm** [comment]
iraf basically does it by dividing up every frame into smaller regions which is handled in the gist above.   There has been an outstanding task to include a combiner task which the gist could include or alternatively to write it a completely different version in cython that would handle it pixel by pixel.   It hasn't been very high on the priority list right now, but any help with it would also be appreciated.

**Comment by indiajoe** [comment]
May be I shall try to write a wrapper function which will do the procedure done in the gist. Which we can then use inside the code for average, median (or any future) combine methods of combiner.py.
.

**Comment by mwcraig** [comment]
Thanks, @indiajoe , that would be awesome!

**Comment by indiajoe** [comment]
Got some time today to write the decorator (I have kept it here temporarily: https://gist.github.com/indiajoe/24d916c3450f448f6b0e )
But I think I understood the problem wrongly. Memory usage at which stage are we trying to reduce?
If I understand correctly when we create a combiner object it creates an internal 3D maskedArraycube.  While taking median or average, does it really create another copy of that array? If so using the decorator around those functions will help. 
But now I have a feeling, the aim was to prevent the combiner from creating a full 3D cube of the data in the first place when it initialises. Not at the mean or median calculation step. Am I right? If so, function decorator might not be the solution. We will need to make a convenience function to create multiple combiner objects like the script in original gist does.

**Comment by mwcraig** [comment]
@indiajoe -- you are correct that combiner creates an internal copy as a masked array, so the goal would be to break the array into chunks. Also, if you could take a quick glance at http://astropy.readthedocs.org/en/stable/development/codeguide.html#coding-style-conventions that would be great -- main thing I noticed in the gist is that you are using camel case (which we've avoided).

Thanks again!

**Comment by indiajoe** [comment]
@mwcraig , @crawfordsm -- I have written another convenience class  which will create a new combiner instance for each sub tile, set the properties etc.. 
https://github.com/indiajoe/ccdproc/commit/060f046518b35965649883857f78c4d8fe8c2aff

The code above is just to show the structure and outline of the planned implementation. 
I haven't tested it yet, and I shall also correct it to follow astropy coding style guidelines. 
Before that, I thought it might be a good idea to ask for any feedback and suggestions on this approach?

**Comment by mwcraig** [comment]
Was this closed by #218 ?

**Comment by indiajoe** [comment]
I think, it is solved. #218 wasn't a cython implementation as suggested earlier in this issue. But it solves the problem.

**Comment by mwcraig** [comment]
@crawfordsm -- can you please close this if #218 fixed it? Thanks!
