### ISSUE TITLE
Small documentation fixes

### ISSUE THREAD

**Issue by mwcraig** [astropy/ccdproc#185]
This is meant to start a collection of these that will be fixed in a single PR...

- [x] https://github.com/astropy/ccdproc/commit/7c15bd6a135df83462c129aaaa8ba75d1b6b3329#commitcomment-8032381

**Comment by souravsingh** [comment]
I wish to do this.How do I start?

**Comment by mwcraig** [comment]
Hi @souravsingh -- thanks for volunteering! I won't have time to give you detailed help until Friday or Saturday. In the meantime you could take a look at the contributing documentation for astropy at http://astropy.readthedocs.org/en/stable/development/workflow/development_workflow.html

If I don't reply again by Saturday please remind me!

**Comment by crawfordsm** [comment]
- [ ] update CCDData documenation where it refers to NDData
- [ ] add example of CCDData arithmetic to documentation and warning about how WCS is handled

**Comment by souravsingh** [comment]
Thanks for the checklist @crawfordsm

**Comment by mwcraig** [comment]
@crawfordsm -- could you also do this?

 + [ ] In the last numbered point of https://github.com/astropy/ccdproc/blob/master/docs/ccdproc/image_management.rst add a note that overwriting does not work on Windows. 

Seems to make more sense than adding a separate known issues page for one known issue...let me know if you want me to do it.

**Comment by crawfordsm** [comment]
will do
