### ISSUE TITLE
no wcs setter

### ISSUE THREAD

**Issue by crawfordsm** [astropy/ccdproc#203]
In ccddata, wcs is current an attribute with no way of setting it such that:
    ccd.wcs = wcs 
currently fails

**Comment by mwcraig** [comment]
To close this we want to add a setter as described, e.g. in http://www.programiz.com/python-programming/property in the last code example.

An example in ``ccdproc/ccddata.py`` is at https://github.com/astropy/ccdproc/blob/master/ccdproc/ccddata.py#L112

(it is the `CCDData` object that needs the WCS setter)
