### ISSUE TITLE
arithmatic on data with wcs

### ISSUE THREAD

**Issue by crawfordsm** [astropy/ccdproc#204]
Current arithmatic between two `CCDData` objects is  not possible unless they have the exact same wcs.   This is due to a line in 
    if self.wcs != operand.wcs:

I'm not sure what that comparison entails, but it would seem that at times you would want to be able to subtract fits files that have different wcs values.    For example, when calibrating between calibration frames and science frames.

**Comment by hamogu** [comment]
+1 fir a way to do arithmetic with non-matching WCSs. (On a pixel-by-pixel basis.)

**Comment by dokeeffe** [comment]
+1 fir this. Flats and Darks will never have the same WCS as image frames.

**Comment by mwcraig** [comment]
I'll have to look into this again...we are clearly able to do this in ``ccdproc.subtract_dark``, for example. Turns out the comparison is essentially meaningless anyway because `wcs.WCS` does not implement `__eq__`...

**Comment by dokeeffe** [comment]
That would be great thanks! I'm basically trying to do `ccdproc.subtract_dark` using two `ccdproc.CCDData` instances which are loaded from fits files (master-dark and light files).

**Comment by crawfordsm** [comment]
I'll be opening a small pull request at `NDArithmeticMixin`to try to remove this exception being raised for this as that is where the problem is.  However, if this isn't fixed and released there by the time we are ready with 0.4, we will implement meant a work around in ccdproc

**Comment by crawfordsm** [comment]
Closed by #285
