### ISSUE TITLE
create list of contributors and populate from pull requestes

### ISSUE THREAD

**Issue by mwcraig** [astropy/ccdproc#213]

**Comment by Punyaslok** [comment]
Hi! I'm a newbie to Open Source.
Can you tell me how you're planning on executing this?
Do you plan on extracting all the names of contributors with merged pull requests for storage/display?

**Comment by souravsingh** [comment]
@mwcraig SymPy has a script which allows for adding Authors to the list based on the logs from git.It would be nice if we can make use of the script.

**Comment by mwcraig** [comment]
@souravsingh -- that sounds like a good plan, do you want to give it a try and open a PR? I think what we had in mind is a file like https://github.com/astropy/astropy/blob/master/docs/credits.rst

I don't think we need a copy of the script to do so in ccdproc itself, but if you could document how you generate it in the [ccdproc wiki](https://github.com/astropy/ccdproc/wiki) when you create the PR that would be great!

**Comment by souravsingh** [comment]
I have sent the PR. The PR is available at #313
