### ISSUE TITLE
Allow to chose a function for uncertainty calculation in Combiner

### ISSUE THREAD

**Issue by bsipocz** [astropy/ccdproc#224]
Along the logic of the optional `median_func` and `scale_func`, there may be room for choosing the uncertainty function to be different than the default in `median_combine()` and `average_combine`.

**Comment by MSeifert04** [comment]
Both combination functions contain an `uncertainty_func` in the 1.0.x branch: [`median_combine`](https://github.com/astropy/ccdproc/blob/master/ccdproc/combiner.py#L303) and [`average_combine`](https://github.com/astropy/ccdproc/blob/master/ccdproc/combiner.py#L379)
