### ISSUE TITLE
Delete WCS keywords from header after creating WCS object from FITS

### ISSUE THREAD

**Issue by mwcraig** [astropy/ccdproc#232]
Right now the WCS object is created but the keywords are left in the header. That seems undesirable because the two can, in principle, get out of sync. Right now the code treats the WCS attribute as the correct ones, but the ambiguity would be removed if the header keywords were removed.

**Comment by crawfordsm** [comment]
As to our conversation: the meta data and the WCS information should stay current with each other, so if we could have something where the meta data updates when the WCS updates would be ideal.

**Comment by crawfordsm** [comment]
Fixed upstream and will be fixed once #510 is closed

**Comment by mwcraig** [comment]
Closed by #528
