### ISSUE TITLE
Remove extensive discussion of Keyword class in "Getting Started" section of documentation

### ISSUE THREAD

**Issue by mwcraig** [astropy/ccdproc#235]
It gets two sentences and examples but is largely irrelevant (and unused in ccdproc)

**Comment by souravsingh** [comment]
I can make a quick pull request for this. @mwcraig Can you tell me if anything more needs to be written?

**Comment by mwcraig** [comment]
@souravsingh -- great! I think all you need to do is delete the parts of the documentation that mention the `Keyword` class. Initially we thought it might be useful but it turned out not to be.

**Comment by Punyaslok** [comment]
@mwcraig Can you please tell me why some checks were not successful even though I only modified one file, which was a .rst file ?

**Comment by crawfordsm** [comment]
closed by #296
