### ISSUE TITLE
ImageFileCollection iterators return full path to filename, not just the file name

### ISSUE THREAD

**Issue by mwcraig** [astropy/ccdproc#248]
Was surprised today when writing tables inside a `.hdus` loop that the files I was writing were being written to the directory with the original images, not the directory I was working in in the notebook.

The problem was that in a loop like this:

```python
image_collection = ImageFileCollection('/Users/mcraig/Documents/Data/feder-images/fixed_headers/2015-05-21-reduced',
                                      keywords='*')

for hdu, fname in image_collection.hdus(return_fname=True, imagetyp='LIGHT', object='ey uma'):
    print(fname)
```

the returned `fname` is the *full path* to the file rather than just the file name.

**Comment by mwcraig** [comment]
@crawfordsm -- there is a question here, I think: what *should* be returned? It is easy to generate the full path from the file name and the location with `os.path.join(image_collection.location, fname)`....

**Comment by crawfordsm** [comment]
I think I discovered this as well and I was doing something similar to the joining of the paths.   perhaps there should be some option for being able to specify the output path?

**Comment by crawfordsm** [comment]
And then a default if it is not specified.   There is also the problem that if it is in the same directory as the raw data, when you read in stuff again, you will get that file as well (if there is some change in the name) or overwrite your raw file which I'd classify as very, very bad
