### ISSUE TITLE
Fix CHANGES.rst, which incorrectly lists some changes in the wrong release

### ISSUE THREAD

**Issue by mwcraig** [astropy/ccdproc#251]
Some of the changes committed in #250 were added to 0.3.1 instead of 0.3.2 (which has since been superceded by 0.3.3 anyway due to errors in the changelog for 0.3.2)

**Comment by mwcraig** [comment]
should we release an 0.3.3.post1 to fix this???

**Comment by crawfordsm** [comment]
Um, I don't know.  How bad is it?  And how much work?

**Comment by mwcraig** [comment]
A couple things that are really in 0.3.3 are listed under 0.3.1. I'll definitely fix it in master, but maybe not bother with fixing on 0.3.x unless we end up doing another release there? All of the fixes are listed in the changelog for 0.3.3....
