### ISSUE TITLE
Python 3.5 compatibility?

### ISSUE THREAD

**Issue by conor-byrne** [astropy/ccdproc#254]
Just attempted to install from anaconda with:
`conda install --channel https://conda.anaconda.org/astropy ccdproc`

which gave

```` 
[Anaconda3] C:\Users\Conor>conda install --channel https://conda.anaconda.org/astropy ccdproc
Fetching package metadata: ......
Solving package specifications: ............
Error: Unsatisfiable package specifications.
Generating hint:
[      COMPLETE      ]|##################################################| 100%


Hint: the following packages conflict with each other:
  - ccdproc
  - python 3.5*

Use 'conda info ccdproc' etc. to see the dependencies for each package.

Note that the following features are enabled:
  - vc14
````

If you're working on it, that's fantastic. I really don't want to seem ungrateful.
Thanks!

**Comment by crawfordsm** [comment]
Just noticing that we don't have python 3.5 in our test suite, and I'm not sure if a conda package has been created for it yet but @mwcraig should be able to answer that.  Thanks for bringing this up and we will try to get it fixed soon.

**Comment by mwcraig** [comment]
> If you're working on it, that's fantastic. I really don't want to seem ungrateful.

We are grateful for every user, believe me! 

I'm downloading the latest microsoft compiler for Windows (compiler changed in 3.5) and will give it a try. *Shouldn't* be an issue for ccdproc since it is pure python, but I've held off on updating the automated conda-builder until I can try out compilation on Windows.

**Comment by mwcraig** [comment]
@conor-byrne -- forgot to say thanks for reporting, and in the meantime you should be able to do `pip install ccdproc` without any problems.

**Comment by conor-byrne** [comment]
Cheers guys, much appreciated. Thanks again for your work!

**Comment by mwcraig** [comment]
@conor-byrne -- there is now a python 3.5 conda package for ccdproc on the `astropy` channel, 64-bit windows, mac and linux. 

Let me know if you run into any problems with it.
