### ISSUE TITLE
fits_section does not allow for '*' indexing

### ISSUE THREAD

**Issue by evertrol** [astropy/ccdproc#264]
The `fits_section` argument used in `subtract_overscan` and `trim_image` does not allow for the use of an asterisk wildcard to indicate all rows or columns. Instead, it uses the Python convention for indicating this, using a lone double colon.

This is fairly easily resolved while still allowing for the `:` syntax, by replacing all `*` with `:` halfway the `slice_from_string` function. For example:

    ...
    no_space = no_space.strip('[]')                                                            
    if fits_convention:                                                                        
        no_space = no_space.replace('*', ':')                                                  
    string_slices = no_space.split(',')           
    ...

This should even work for the case of `[*:2, *]`, which correctly transforms to `[::2, :]`.  It will fail, however, for a case like `[-*, *]`, which is a typical FITS section style for flipping an axis. 

I've created this issue to see if there is interest in supporting this, and what varieties of `*` indexing it should support.

(Examples of FITS sectioning can be found at https://heasarc.gsfc.nasa.gov/docs/software/fitsio/c/c_user/node94.html .)

**Comment by crawfordsm** [comment]
Thanks for the feedback @evertrol .   If you have a chance, please feel free to to put in a pull request with this update.  If not, we will see if it can be added soon.   I think the code you added looks like it would work for most cases with a small test added for it.   

Hmm, probably could open a second pull request to handle the special case of `[-*,*]`

**Comment by evertrol** [comment]
Not a problem: I can implement a PR possibly tomorrow, or later this week.

For the special `[-*,*]` case, I wonder if the following cases are valid FITS sectioning syntax:
- `[-*:2,*]`
- `[*:-2,*]`

I suspect the former is, while the latter isn't. The link given above is not that explicit about the syntax, but from the example that uses `[*:2, 512:256:2]`, I don't think FITS uses, or even allows for, negative step sizes.

That last example also makes me wonder if this syntax is supported: start being larger than stop, but with a positive increment. Seen the handling of FITS sections in ccdproc, I guess this won't work either (haven't tried though).

Obviously, all these special cases are unlikely to occur, so it raises the question in how far ccdproc should support FITS sectioning syntax.

I'll give it a try with a PR, and see in how far I can reasonably accommodate these special cases.

**Comment by mwcraig** [comment]
Closed by #265
