### ISSUE TITLE
print function in combiner.combine() can be rather noisy

### ISSUE THREAD

**Issue by evertrol** [astropy/ccdproc#266]
The explicit use of `print()` in `combiner.combine()` can't be turned off, and can cause noisy output where it's not wanted.

The offending lines are https://github.com/astropy/ccdproc/blob/master/ccdproc/combiner.py#L475-L476 and https://github.com/astropy/ccdproc/blob/master/ccdproc/combiner.py#L492

The latter could become `logging.info(...)` or `astropy.log.info(...)`.

For the former, I doubt the exception needs to be caught and printed at all, and the exception can just bubble up to the user. The usual error message tends to as clear or clearer (if the input path happens to be directory, ccdproc will still print a message saying the file can't be found, next to a message saying it's a directory). Also, in line https://github.com/astropy/ccdproc/blob/master/ccdproc/combiner.py#L517 , the exception isn't caught at all for the rest of the files in the input.

**Comment by crawfordsm** [comment]
Good point @evertrol -- something that I missed in the initial review.  The first one should just be an exception and then second should use astropy.log.info .   Thanks for raising it and feel free to submit a PR fixing it.
