### ISSUE TITLE
hdu or ccddata in imagefilecollaction

### ISSUE THREAD

**Issue by crawfordsm** [astropy/ccdproc#270]
Should ImageFileCollection geneator produce hdu's or CCDData objects?

**Comment by mwcraig** [comment]
It would be nice to keep the `hdus` option, but would be easy enough to add another generator because they all (`data`, `hdus`, `headers`) share the same code under the hood and differ only in what they return.

Maybe an `images` generator?

**Comment by MSeifert04** [comment]
@crawfordsm #405 is merged, did that PR fully adress your issue?

**Comment by MSeifert04** [comment]
@crawfordsm I'm closing this because I guess that's fixed by #405. Feel free to reopen it if you think it's not adressed yet.
