### ISSUE TITLE
Arithmetic between CCDData objects with WCS fails even with identical WCS

### ISSUE THREAD

**Issue by AnthonyHorton** [astropy/ccdproc#283]
The CCDData arithmetic functions cannot be used with CCDData objects that have WCS even if the WCS are the same. Example:

    In [10]: ccd = ccdproc.CCDData.read(path, unit='adu')
    WARNING: FITSFixedWarning: 'datfix' made the change 'Changed '' to '2014-10-17''. [astropy.wcs.wcs]
    
    In [11]: ccd2 = ccd.copy()
    
    In [12]: result = ccd.subtract(ccd2)
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    ...
    ValueError: WCS properties do not match
    
The cause of the problem is upstream; `CCDData._ccddata_arithmetic` inherits from `astropy.nddata.NDArithmeticMixin._arithmetic` which checks for equivalence of the WCS of the arguments (`if self.wcs != operand.wcs: raise ValueError("WCS properties do not match"`) however this check always fails because `astropy.wcs.WCS` does not implement `__eq__()` or `__ne__` so this check is effectively a check for identity, not equivalence.  Demo:

    In [13]: w = ccd.wcs
    
    In [14]: w2 = copy.deepcopy(w)

    In [15]: w == w
    Out[15]: True
    
    In [16]: w == w2
    Out[16]: False

I'll file an issue with `astropy.wcs.WCS` and try to fix it there but felt I should also report it here.

**Comment by dokeeffe** [comment]
When 204 gets fixed it will probably fix this too 
https://github.com/astropy/ccdproc/issues/204

**Comment by AnthonyHorton** [comment]
@dokeeffe Huh, somehow didn't find #204 when I search for existing issues describing this problem. This is a closely related but slightly different issue, though, i.e. implementing `__eq__()` and `__ne__` in `astropy.wcs.WCS` would fix this but not #204 whereas removing the exception from `astropy.nddata.NDArithmetic._arithmetic` WCS equivalence check would fix both (in a somewhat unsatisfactory way).

**Comment by MSeifert04** [comment]
@AnthonyHorton - I'm currently working on the ``NDArithmeticMixin`` to make the ``check_wcs`` optional. But I still think there should be an ``__eq__`` function in ``astropy.wcs.WCS`` since even if the check is optional it would be nice to have some way of comparing two ``WCS`` instances.

**Comment by AnthonyHorton** [comment]
@MSeifert04 I agree, I think the both are needed.  Making the WCS check in `NDArithmeticMixin` optional handles the issue with flat fielding, dark subtraction, etc. (i.e. #204) but for the rest of the time when you do want to ensure you have compatible WCS a functional `__eq__()` for `astropy.wcs.WCS` is required.

**Comment by crawfordsm** [comment]
closed by #285

**Comment by AnthonyHorton** [comment]
@crawfordsm I don't think this should be closed by #285.  That handles the case where you want to disable WCS checking (i.e. #204) but doesn't solve the problem for when you do want WCS checking (this issue).  That still won't work due to upstream issues (astropy/astropy#4499) which will be fixed by astropy/astropy#4503 (for 1.0.x/1.1.x) or @MSeifert04's astropy/astropy#4272 for 1.2+

**Comment by crawfordsm** [comment]
Sorry, I should have been descriptive in closing it.   As there are open pull requests upstream to fix this and #285 should work with those fixes, I've closed this as there isn't anything more to do in ccdproc.  If you feel it should stay open until those upstream issues are merged, I'm happy to re-open it.

**Comment by AnthonyHorton** [comment]
@crawfordsm No worries, just a different interpretation of what closing the issue means I think.  My personal inclination would be leave it open until an upstream fix is merged so that it's more obvious to a user searching here that this is an current issue without a fix available, yet.  I don't have strong feeling on this though and hopefully it'll be moot soon, astropy/astropy#4503 is ready for merging and astropy/astropy#4272 probably isn't far off either.
