### ISSUE TITLE
Drop support for python 2.6 and 3.3

### ISSUE THREAD

**Issue by mwcraig** [astropy/ccdproc#288]
We should definitely drop 2.6. I don't see much point in continued support for 3.3. Would help address the fails in #287

**Comment by crawfordsm** [comment]
Agreed.

**Comment by crawfordsm** [comment]
closed by #287

**Comment by bsipocz** [comment]
@crawfordsm @mwcraig - Does this issue also means that the 2.6 workarounds can/should be removed?

**Comment by mwcraig** [comment]
Yes, that would make sense.
