### ISSUE TITLE
Drop support for older versions of numpy (1.7 and 1.8)

### ISSUE THREAD

**Issue by mwcraig** [astropy/ccdproc#289]
By this I mean drop testing, and update the minimum version in setup.py. Also helps with #287.

**Comment by mwcraig** [comment]
Just drop this from tests, no need to put the restriction in `setup.py`

**Comment by bsipocz** [comment]
Since #287 is removed these from the test matrix, and got merged, this can be closed.

**Comment by crawfordsm** [comment]
closed by #287
