### ISSUE TITLE
CCDData Arithmetics (add/subtract) with Quantity

### ISSUE THREAD

**Issue by MSeifert04** [astropy/ccdproc#291]
I think something is wrong when using CCDData arithmetics with Quantities (at least addition and subtraction):

```
import ccdproc
import astropy.units as u
ccdproc.CCDData(10, unit='meter').add(1*u.cm).data
#Out: 11
ccdproc.CCDData(10, unit='meter').add(1*u.cm).unit
#Out: Meter
```

This should be 10.01 meters.

**Comment by Punyaslok** [comment]
Hi! I would like to work on this issue. It also happens when when I try among many other units, for example : kg + lb.
`ccdproc.CCDData(1, unit='kg').add(1*u.imperial.lb).data` gives output as 2. Is there a conversion function built-in or do we have to make them for all the physical quantities ?

**Comment by MSeifert04** [comment]
@Punyaslok - The astropy.units framework provides many ways to convert units. If you would like to work on this issue you can have a look at [astropy 1.2 NDArithmeticMixin](https://github.com/astropy/astropy/blob/master/astropy/nddata/mixins/ndarithmetic.py#L330) for inspiration how one could do it.

**Comment by MSeifert04** [comment]
@Punyaslok - I hope you don't mind that I've pushed a PR concerning this issue. I was working on #305 and thought I might also include a fix for this issue.
