### ISSUE TITLE
Release of 0.4 of ccdproc

### ISSUE THREAD

**Issue by crawfordsm** [astropy/ccdproc#298]
As their have been many updates and a lot of new contributions (thanks everyone!), @mwcraig and I are hoping to release a version of ccdproc at the end of the month (of course this is likely to get slightly delayed).   We have decided to do a feature freeze today and punt any issues that we don't think we will be able to get done or won't get done before the feature freeze.   

We will still try to address any bug fixes that come up during that time and improve the code.  But if there is anything you think is critical for the release, then please let us know here.  The two major features we are hoping to include are #129 and #196. 

Also, the big area that will help is having examples of using ccdproc,  improvements to the documentation, and tests against other reductions.  So if you do have any examples of those, please consider sharing them.  

cc'ing @MSeifert04 @bsipocz @AnthonyHorton @evertrol @indiajoe but please anyone else I have forgotten please let us know your thoughts.    And once again, thanks for everyone's help!

**Comment by bsipocz** [comment]
@crawfordsm - I'm not sure I'll have time until the end of the month to test ccdproc in production code/data, but happy to help with any infrastructure issues that come up before the release.

**Comment by MSeifert04** [comment]
- #303 should be included for 0.4 (forgot to include the changes.rst)
- #304 if anyone knows how to include the documentation for the ``CCDData.read`` and ``write`` this should be included.
- #291 would be nice to fix this as well.

**Comment by evertrol** [comment]
Has this now been tagged 1.0 instead of 0.4?

**Comment by mwcraig** [comment]
yes -- and 1.0.1 is now out because of a minor packaging issue.

**Comment by mwcraig** [comment]
Announcement coming as soon as the conda package is built, looking like that will be morning.

**Comment by evertrol** [comment]
Does that also mean the API is considered stable now, and won't change until ccdproc 2.x?
(Asking since I've recently bumped into such an issue where a version 1.0 had an API change in what should I'd normally consider a bug-fix release.)

**Comment by mwcraig** [comment]
Yes; we'll try hard not to make unintentional API changes. I could imagine backwards-compatible API changes happening in minor releases like 1.1 -- for example, adding a keyword argument to a function whose default value preserves the old behavior -- wand adding new functionality into minor version releases.

If wider usage some big API problems I'd lean towards a 2.0 release (though I haven't discussed this with @crawfordsm, so there may be some better solution if that were to happen).

**Comment by crawfordsm** [comment]
@evertrol , I'm going to open a separate issue, but yes, for the v1.0 release I expect to have  stable API.   Any changes to the existing functions will either be behind the scenes or will add a parameter where the default functionality does not change how it works.
