### ISSUE TITLE
Combiner and resulting uncertainty

### ISSUE THREAD

**Issue by MSeifert04** [astropy/ccdproc#309]
I've used the ``ccdproc`` combiner today and compared it to what I had for results using my custom combination (before I found out about ccdproc) and noticed the uncertainty of the ``ccdproc``-combine result is much higher than my custom one. After some investigation I found a possible explanation:

I've always used ``1/sqrt(n-1) * np.std(...)`` instead of ``np.std(...)``. I always thought the standard deviation would be the uncertainty of a single value and the uncertainty of the combined values should be divided by the square-root of the number of combined points (corrected for finite population).

If that's not the case this issue can be closed but I wasn't sure and searching the internet didn't help either.

**Comment by crawfordsm** [comment]
@MSeifert04 you are right.  That's a bug and should be fixed.
