### ISSUE TITLE
Documentation for the `add_keyword` argument is confusing

### ISSUE THREAD

**Issue by evertrol** [astropy/ccdproc#310]
The documentation for the `add_keyword` argument used in various functions is incorrect, or at least confusing. It says the following:

> Set to None to completely disable logging. Default is to add a dictionary with a single item

The function signature, however, shows the following:

    ccdproc.somefunction(..., add_keyword=None)

That indicates that the default is already `None`, and the two sentences in the doc string disagree with each other.

It took a bit of searching and reading through [`log_to_meta`](https://github.com/astropy/ccdproc/blob/master/ccdproc/log_meta.py#L30) to find out what is really supposed to happen:
- setting `add_keyword` to `None` does indeed prevent logging
- setting it to a string, `Keyword` or dict uses that as logging
- *not supplying the keyword* uses a default logging

The last bit was the suprising part for me, and comes about in the way that `add_keyword` is supplied to the various functions, by altering the function signature (and docstring), and then later checking for the function's signature.

Possible fixes:
- change the doc string. For example: "Set to None to completely disable logging. Leave the keyword out to add a dictionary with a single item".
  This, however, would still suggest the default is `None` (from the function signature), and disables logging if `add_keyword` is not supplied. I doubt there's a clear way to document the precise behaviour.
- Change the [default value](https://github.com/astropy/ccdproc/blob/master/ccdproc/log_meta.py#L56) to `False`.
- Be more explicit, and have a default of `add_keyword=True`. This enables automatic logging. Setting it to `None` or any falsely value (`False`, `0`, `""` etc) disables logging completely. Any other value for user supplied keywords.
- Be even more explicit, and forego the `@log_to_metadata` decorator completely. Supply `add_keyword=None` (or `True`) to every function (and copy-paste the doc string section), then hand out the keyword logging to a separate function which does what the core of `log_to_metadata` does.

My preference order of solutions is in reverse order: I like the fourth option best, even if there is some redundancy, since it makes things very clear, and doesn't alter the function's signature. The third option is also more explicit than the other solutions, which is why it has my next preference.

Once judgement has been passed on which route to take, I'm happy to put in a PR.

**Comment by crawfordsm** [comment]
Sorry @evertrol I thought I did reply to this.  My option would be for number 3 right now if you want to see this fixed in the next release.   I think that would result in the least amount of major changes to the code and little change in how the functionality works.   

If that isn't satisfactory close to this, we can then review how the keyword logging is handling for the next release and see if any major changes are needed.

**Comment by crawfordsm** [comment]
Closed with #312, but feel free to re-open or open a new issue if you do feel like this should be addressed differently in the future.  Thanks @evertrol !
