### ISSUE TITLE
Shortcuts for image manipulation

### ISSUE THREAD

**Issue by crawfordsm** [astropy/ccdproc#316]
It would be nice to have some shortcuts for doing simple image manipulation like shift, magnify,or rotate.  These likely already exist in other packages and just need to be wrapped for CCDData objects

**Comment by mwcraig** [comment]
I think this is out-ofscope for ccdproc. We could document that reproject is the right way to do it. Once repropject moves into core we could consider adding some convenience methods maybe?

So perhaps punting is preferable to closing...

**Comment by crawfordsm** [comment]
This functionality is in or will belong in reproject project: https://reproject.readthedocs.io/en/stable/

Closing this, but we should add more links to reproject.
