### ISSUE TITLE
Tiny bug in AUTHORS.rst

### ISSUE THREAD

**Issue by augustfly** [astropy/ccdproc#331]
Just a small bug in ccdproc/AUTHORS.rst

> (If you have contributed to the ccdproc project and your name is missing,
> please send an email to the coordinators, or
> `open a pull request for this page <https://github.com/astropy/ccdproc/edit/master/credits.rst>`_
> in the `ccdproc repository <https://github.com/astropy/ccdproc>`_)

=>

> (If you have contributed to the ccdproc project and your name is missing,
> please send an email to the coordinators, or
> `open a pull request for this page <https://github.com/astropy/ccdproc/edit/master/AUTHORS.rst>`_
> in the `ccdproc repository <https://github.com/astropy/ccdproc>`_)

**Comment by crawfordsm** [comment]
Nice catch @augustfly and thanks!

**Comment by augustfly** [comment]
no problem. i'm starting a project to log how software teams craft author lists and deal with credit, so I tend to notice/follow these kind of links!

**Comment by crawfordsm** [comment]
It was a great catch.  We have just had discussions about this and if you'd like to know any details, I'll be happy to share them.
