### ISSUE TITLE
meta attribute is inconsistent

### ISSUE THREAD

**Issue by evertrol** [astropy/ccdproc#336]
The fact that the `meta` attribute can be `dict`, an `OrderedDict` or a `astropy.io.fits.Header` instance has irked me on occasions. In particular because the three types are incompatible with each other.

This means at times that one has to either do a manual conversion, or test the type of the meta attribute, before performing some operations. Case sensitivity may be one issue to run into (issue #156 indicates `meta` should be case sensitive); _comment_ or _history_ keywords may be another thing.
(That same issue also indicates a willingness to move away from FITSness of `CCDData`, though this may not always be doable.)

My suggestion would be use a standard `dict` only. This means a loss of information converting from an `OrderedDict`, but I doubt that that will be really an issue.
For a `Header` instance, there would be a need to decide on 
- history and comment keywords. I would probably create a separate issue to make these list of strings in special `meta` keys, if there is an overall approval of this issue. Note: `astropy.table.Table` has `meta["comments"]` (note the plural key), so it'd be good to use that approach.
- should the keywords be lower-cased, or stay upper-case (I don't like using CAPITALS in my code for various reasons, so I prefer lower-case).

For going from a `dict` to a `Header` when writing to a FITS file or HDU, I suggest issuing a warning in case duplicate keywords are found (and thus lost). This would be the case for `dict` keys that are the same except for their case. Currently, this is silently ignored and it is random what is written to the actual `Header`.
_history_ and _comment_ keywords can be written with the above list approach (arguably, handling "history" and "comments" keys in `meta` differently is a FITSness; this is probably something I can live with, in particular because upon writing to FITS, any value can be written as a (1 element) list of strings).

Perhaps this `meta` inconsistency is a non-issue for the majority of people (in which case this issue can be quickly closed), but otherwise I'd be happy to create a PR for this. There may be the downside of some loss of backward compatibility, for example, if people have code that uses something like `ccd.meta.add_history("blah blah")`, but my feel is that that is minimal.

**Comment by crawfordsm** [comment]
I've typically mainly used the meta attribute basically as a FITS header and so I am hesitant to move too far away from that.   From my experience, this is what the average user will expect (as they will be opening up data from a FITS file I would guess)  but that is totally due to my own bias.  

I'd agree that having an object that can operate in multiple different ways is bad for the downstream user.   However, what the best way that object should be I'm not sure about and would seem like a major change to the API so at the very least, something for a version 2.0 release.  

It also might be best to take a look at what the overall functions of the header/meta object should do, and what would match those as best.

**Comment by evertrol** [comment]
I agree that most people will use data read in from a FITS file, and thus have a FITS header object as meta.

But if there is ever an alternative data format (HDF5, NDF), a FITS header will probably be inadequate. (It's also unPythonic, with e.g. its case insensitive keys. Which can be confusing for people with Python knowledge bit little to no FITS knowledge.)
The aforementioned issue #156 also suggests moving away from FITS, abstracting meta.

I may have a play around with altering meta and see which unit tests still pass, as a first indication to see whether a `dict` can fulfill the overall functionality for meta.

**Comment by mwcraig** [comment]
I think the main argument for allowing (but not requiring) the metadata to be a FITS header was to ensure that they could round-trip reasonably intact. IIRC #156 came from the API doc we put together for ccdproc, and at the time I know I was thinking of the meta as a particular type. 

We ended up duck typing after trying (I think) an OrderedDict, a dict and something that was sort of FITS Header-like. 

I'm a little reluctant to end the ability to round-trip FITS headers. HISTORY and COMMENT end up, in some cases, having meaning only to the extent that they happen in order; WCS keywords tend to be the same way (all of this assumes a human is actually going to read the FITS file at some point which may not be the case).

What about an argument to `CCDData.read` that allows one to indicate what type you want the return meta to be? For example, `CCDData.read(...., meta_as=dict)` or `OrderedDict` or whatever you want?

**Comment by evertrol** [comment]
A argument may indeed work (possibly not only to `CCDData.read`, but I think that's really the only place where `meta` is implicitly created. I'll have an attempt at this.)

I'm also looking at the possibility of having the `meta` attribute as a `dict`, while having the `header` attribute always as a `fits.Header`. Since these are accessed through properties, it may be possible to transparently update both when only one is updated in code (though this may cause confusion, and possibly will run into the incompatibilities between the two).
You could then access either `.meta` or `.header`, depending on the type you want.

**Comment by crawfordsm** [comment]
@evertrol if you have a chance and want to suggest a PR, I think it would be interesting to see it and further discuss it.   I think the one thing that we would want is to keep the connection between `.meta` and `.header` even if one is always a dict and one is always a FITS header-like.

**Comment by mwcraig** [comment]
@evertrol -- could you provide an example of where you've run into the header type inconsistency being an issue? We're trying to better understand the broader problem that your PR is solving.

I do understand that there is is an issue that needs to be addressed regardless of issuing a warning if data is going to be lost when meta is converted to a `Header` (assuming meta isn't already a `Header`) and that there is an issue you have run into repeatedly that it would be nice to help address.

**Comment by evertrol** [comment]
@mwcraig There is no direct example of where this becomes an issue for me: I can easily work around things, since I can keep track of the type of `meta`, or simply check it beforehand.

It's mostly an itch that I'd like to scratch, since from an API/developer point of view, having an attribute behaving in multiple ways (depending on what's been done to the CCDData object), feels awkward. I'd also like to avoid `if isinstance(ccd.meta, fits.Header):` things in my code (duck-typing doesn't work between `fits.Header` and a `dict`).

The PR isn't solving much: it's merely trying to keep `.meta` always a `dict`, and `.header` always a `fits.Header`, *and* keeping them in sync when one of them gets modified. That can resolve some of the ambiguity what the type of `.meta` is, though I can't say I like the solution much.

If there are plans to make the `NDData.meta` attribute something that can incorporate both a `dict` and a `fits.Header` (though I guess the case-insensitivity of keywords can never be fully resolved), then it's indeed up to the writers and readers to do the proper conversion, and this issue goes away (since `.meta` is then of a consistent type).

**Comment by mwcraig** [comment]
Closing, CCDData has now moved to astropy.nddata, please re-raise on the astropy/astropy if this is still an issue.
