### ISSUE TITLE
Docstring formatting issue

### ISSUE THREAD

**Issue by cdeil** [astropy/ccdproc#338]
Have a look at  http://ccdproc.readthedocs.org/en/latest/api/ccdproc.ccd_process.html ... there's some formatting issues with the docstring:

<img width="697" alt="screen shot 2016-03-27 at 22 35 23" src="https://cloud.githubusercontent.com/assets/852409/14071679/47dc834c-f46c-11e5-9053-b7889bf33943.png">

For the bullets you have to add an empty line above.
For the parameter types, you have to add a space before the colon to make them appear correctly.

@bsipocz - Is there a way to catch such issues in the Sphinx build and on travis-ci?
Probably we also have 100s of those in Gammapy and other affiliated packages?
Would be really nice if catching such things could be automated.

**Comment by bsipocz** [comment]
@cdeil - even if there's a way I don't know what it is rather than the reviewer spots them in time.
 Syntactically both ways are right and sphinx just happens to render one of them.

**Comment by crawfordsm** [comment]
NIce spot @cdeil 

Maybe a utility to add to astropy helpers to run to look for things like this?

**Comment by bsipocz** [comment]
@crawfordsm - I'm :-1:  on this as I don't  think that astropy_helpers is a place for convenience scripts like this.
A more appropriate place for it would be https://github.com/astropy/astropy-tools.

**Comment by cdeil** [comment]
I've split the feature request for a tool that automatically checks docstring formatting to
https://github.com/astropy/astropy-tools/issues/11

**Comment by MSeifert04** [comment]
I haven't seen this issue but I think in #341 this will be fixed. Is there a way post-first-commit to link this issue as `Fixes ...` to the PR?

**Comment by bsipocz** [comment]
@MSeifert04 - You can do it in the commit message of any of the commits. [0] Alternatively you can always edit the text of the PR, and do it there. [1]

[0] - https://help.github.com/articles/closing-issues-via-commit-messages/
[1] - https://github.com/blog/1506-closing-issues-via-pull-requests

**Comment by MSeifert04** [comment]
@bsipocz Thank you.
