### ISSUE TITLE
Combiner class dosen't work with >2D data.

### ISSUE THREAD

**Issue by Cadair** [astropy/ccdproc#340]
It seems to be because of this: https://github.com/astropy/ccdproc/blob/master/ccdproc%2Fcombiner.py#L97

**Comment by crawfordsm** [comment]
Well, I don't think we were initially expecting it to work with >2D data, so that might explain it.  I don't really see a problem with removing that requirement and generalize the task.  If you have time to submit a PR, please feel free to do so, but if not, I'll add it to the todo list.
