### ISSUE TITLE
CCDData images returned by combiner cannot be written as FITS files

### ISSUE THREAD

**Issue by mwcraig** [astropy/ccdproc#351]
The details needed to reproduce this are below, but at a high level, this is what is going wrong (and why, I think, we didn't notice it earlier).

+ The methods in the `Combiner` class that actually do the combining, like `average_combine`, use (appropriately) the numpy masked functions, e.g. `np.ma.average`, to calculate the `uncertainty`. 
+ The result is, of course, a numpy masked array.
+ We set the `uncertainty` of the combined image to the masked array from the previous step (well, we initialize a `StdDevUncertainty` using the masked array), so that `uncertainty.array` is a `maskedarray`.
+ Converting this to an HDU works just fine, but the `data` for the uncertainty plane is a `maskedarray`.
+ Writing this HDU to a file fails because numpy doesn't know how to convert a masked array to a file.

I think this didn't come up before because we weren't saving the uncertainty plane until recently.

A couple ways I can think of fixing this, comments welcome. The fixes could happen either in `Combiner` or in `to_hdu`:

1. Always convert the uncertainty to a regular array. 
2. Convert the uncertainty to a regular array if there are no masked values, otherwise raise an error.

Thanks to @JuanCab for finding the issue!

To reproduce:

```python
import ccdproc
import numpy as np

a = np.random.randn(100, 100)
ccds = [ccdproc.CCDData(a, unit='adu') for i in range(10)]
c = ccdproc.Combiner(ccds)
foo = c.average_combine()
h = foo.to_hdu()
h.writeto('junk.fits')
```

```python
NotImplementedError                       Traceback (most recent call last)
<ipython-input-10-f693bfeb8482> in <module>()
----> 1 h.writeto('junk.fits')

/Users/mcraig/anaconda/envs/redu-dev/lib/python3.5/site-packages/astropy/io/fits/hdu/hdulist.py in writeto(self, fileobj, output_verify, clobber, checksum)
    689             hdu._prewriteto(checksum=checksum)
    690             try:
--> 691                 hdu._writeto(hdulist._file)
    692             finally:
    693                 hdu._postwriteto()

/Users/mcraig/anaconda/envs/redu-dev/lib/python3.5/site-packages/astropy/io/fits/hdu/base.py in _writeto(self, fileobj, inplace, copy)
    741         if not inplace or self._new:
    742             header_offset, _ = self._writeheader(fileobj)
--> 743             data_offset, data_size = self._writedata(fileobj)
    744 
    745             # Set the various data location attributes on newly-written HDUs

/Users/mcraig/anaconda/envs/redu-dev/lib/python3.5/site-packages/astropy/io/fits/hdu/base.py in _writedata(self, fileobj)
    678         if self._data_loaded or self._data_needs_rescale:
    679             if self.data is not None:
--> 680                 size += self._writedata_internal(fileobj)
    681             # pad the FITS data block
    682             if size > 0:

/Users/mcraig/anaconda/envs/redu-dev/lib/python3.5/site-packages/astropy/io/fits/hdu/image.py in _writedata_internal(self, fileobj)
    555                     output.byteswap(True)
    556                     try:
--> 557                         fileobj.writearray(output)
    558                     finally:
    559                         output.byteswap(True)

/Users/mcraig/anaconda/envs/redu-dev/lib/python3.5/site-packages/astropy/io/fits/file.py in writearray(self, array)
    300 
    301         if hasattr(self._file, 'write'):
--> 302             _array_to_file(array, self._file)
    303 
    304     def flush(self):

/Users/mcraig/anaconda/envs/redu-dev/lib/python3.5/site-packages/astropy/io/fits/util.py in _array_to_file(arr, outfile)
    807     else:
    808         # Just pass the whole array to the write routine
--> 809         return write(arr, outfile)
    810 
    811     # Write one chunk at a time for systems whose fwrite chokes on large

/Users/mcraig/anaconda/envs/redu-dev/lib/python3.5/site-packages/astropy/io/fits/util.py in <lambda>(a, f)
    785 
    786     if isfile(outfile):
--> 787         write = lambda a, f: a.tofile(f)
    788     else:
    789         write = _array_to_file_like

/Users/mcraig/anaconda/envs/redu-dev/lib/python3.5/site-packages/numpy/ma/core.py in tofile(self, fid, sep, format)
   5766 
   5767         """
-> 5768         raise NotImplementedError("MaskedArray.tofile() not implemented yet.")
   5769 
   5770     def toflex(self):

NotImplementedError: MaskedArray.tofile() not implemented yet.
```

**Comment by MSeifert04** [comment]
@mwcraig I'm doing some checks, do you happen to know if this affects only astropy 1.1 or also 1.2 (dev)? I've altered the setter for uncertainties recently (https://github.com/astropy/astropy/blob/master/astropy/nddata/nduncertainty.py#L133) especially to catch these problems.

**Comment by mwcraig** [comment]
I only tried it with 1.1.2, but it does look like it will be fixed in 1.2.

**Comment by MSeifert04** [comment]
Yes, I've installed the dev version of astropy and ccdproc and apart from 6 warnings there is no exception and the file looks "good". I probably need to investigate why 6 warnings. There shouldn't be 6, I expected 2.

**Comment by mwcraig** [comment]
Ah, the joy of coding...

**Comment by MSeifert04** [comment]
ah, at least the 6 warnings are ok. I missed that ``hasattr`` also called ``uncertainty.unit``.

And each ``uncertainty.unit`` checks if a parent is avaiable (1 Warning) and then get's the parents unit (another warning).

Doesn't help solving this Bug though. Should I push a fix or a you planning on providing it?

**Comment by mwcraig** [comment]
I'll never say no to a fix 😄
