### ISSUE TITLE
writing .fts files format not understood

### ISSUE THREAD

**Issue by jmccormac01** [astropy/ccdproc#355]
A while back I submitted a PR for adding .fts support to the image collection code. Today I've finally gotten back to testing ccdproc with some real data. I've spotted that writting .fts files also seems to not be possible, see below:

```python
Traceback (most recent call last):
  File "/Users/James/Documents/PythonScripts/NITES/NewPipeline/process.py", line 59, in <module>
    ccd.write('obj_'+f, clobber=True)
  File "/Users/James/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/astropy/nddata/mixins/ndio.py", line 39, in write
    io_registry.write(self, *args, **kwargs)
  File "/Users/James/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/astropy/io/registry.py", line 393, in write
    'write', data.__class__, path, fileobj, args, kwargs)
  File "/Users/James/.pyenv/versions/miniconda3-latest/lib/python3.5/site-packages/astropy/io/registry.py", line 430, in _get_valid_format
    "{0}".format(format_table_str))
Exception: Format could not be identified.
The available formats are:
Format Read Write Auto-identify
------ ---- ----- -------------
  fits  Yes   Yes           Yes
>>> f
'MJ13553424-S001-R001-C001.fts'
```

I had a look in the CCDData.write code and could not see anything that might cause the issue. A quick grep shows this might come from astropy.io registry. Has anyone else been asking about .fts support?

I tweaked the output filename to be .fits instead and it is fine. It would be nice for all fits extensions to be supported. I can raise this as an issue with the core package if it comes from there.

**Comment by mwcraig** [comment]
@jmccormac01 -- thanks for reporting this. What you fixed before was the list of extensions that `ImageFileCollection` recognizes as fits files....it never occurred to me until your issue that we should probably also make sure we register all of those extensions with the `CCDData` readers/writers!

The magical lines are at https://github.com/astropy/ccdproc/blob/master/ccdproc/ccddata.py#L708

If @crawfordsm agrees, I'll hack that bit up to grab the list of recognized extensions from `ImageFileCollection` and then register all of them for reading/writing (unless @MSeifert04 sees issues with that being done....he is often more careful about these things than me).

**Comment by jmccormac01** [comment]
It never occurred to me at the time of the initial PR that this might propagate into the CCD data handling. I should have realised. Ok great, thank you. Hopefully all three extensions (.fit, .fits and .fts) should be ok.   It would be nice if fits had one extension. This reminds me of https://xkcd.com/927/ ;)

**Comment by bsipocz** [comment]
@jmccormac01 -  Have you tried to pass the ``format`` keyword in your command ``ccd.write('obj_'+f, clobber=True, format='fits')``?

As I see Table.write('zizi.fts', format='fits') works perfectly fine, and it seems to be using the same ``io_registry.write()`` mechanism.

**Comment by jmccormac01** [comment]
@bsipocz your suggestion worked perfectly. 

```python
ccd.write('obj_{0:s}_{1:s}'.format(filt,f), clobber=True, format='fits')
```
where f is the same filename as before.

```python
>>> f
'MJ13553424-S001-R001-C001.fts'
```

**Comment by MSeifert04** [comment]
@mwcraig What about altering the [auto-identifier](https://github.com/astropy/astropy/blob/master/astropy/io/fits/connect.py#L53) to also accept `.fts`. Currently allowed are _case insensitive_ ['.fits', '.fits.gz', '.fit', '.fit.gz'](https://github.com/astropy/astropy/blob/master/astropy/io/fits/connect.py#L73).

Maybe one could also use this `is_fits` in the imagefilecollection?

**Comment by mwcraig** [comment]
>  What about altering the auto-identifier to also accept .fts. Currently allowed are case insensitive '.fits', '.fits.gz', '.fit', '.fit.gz'.

@MSeifert04 -- agree in the long term. In the short run, might just implement `.fts` here to keep things moving.

**Comment by MSeifert04** [comment]
Before this is forgotten because it's now closed: Should I open another issue for astropy? So the `is_fits` recognizes these "unknown" extensions?

**Comment by mwcraig** [comment]
That would be awesome @MSeifert04
