### ISSUE TITLE
Question about minmax rejection in ccdproc.combine

### ISSUE THREAD

**Issue by joshwalawender** [astropy/ccdproc#356]
I'm working on removing IRAF dependency in some code and I want to replace use of the pyraf/IRAF imcombine task.  I need to maintain compatibility with existing code, so I want to implement the rejection options in the same way as IRAF imcombine does.  

For the minmax rejection option, it looks to me as if IRAF and ccdproc treat this very differently.  In ccdproc, it masks pixels with a value above or below a specified threshold.  In IRAF imcombine, it looks to me as if they are removing nlow and nhigh pixels from each set of N values for each pixel in the combination (where N is the number of images being combined), so the number of pixels being averaged would be N-nlow-nhigh (see [IRAF imcombine help page](http://stsdas.stsci.edu/cgi-bin/gethelp.cgi?imcombine)).  Is this the correct interpretation?

If so, what would be the best way to proceed?  I'm happy to work on adding the appropriate functionality to ccdproc.

**Comment by crawfordsm** [comment]
Yes the current min/max just cuts at values and not N values,  If you would like to contribute it (it should be just a small function to add to combine) we would definitely welcome it!

**Comment by joshwalawender** [comment]
Ok, great.  I've already forked the repo and have started putting some code in.  I could eventually use some advice on what to name the method to make it clear what is happening.
