### ISSUE TITLE
How can I produce a master dark from many darks ?

### ISSUE THREAD

**Issue by sylvielsstfr** [astropy/ccdproc#357]
Hi  Steve and Matt,

I am using the ccdproc python package since last week. I understand how to generate a master bias from many bias files. I have checked that the substraction of darks with the master-dark gives the expected residuals xith zero average and very narow RMS.

However, I don't see how i can combine a set of darks having different exposures to produce a master-dark say for a unit exposure.

Do I need to use overscan region, if I already have the masterbias.
I al a little bit confused in your document because I don't understand in which order I should proceed with the tasks.
I would dream to have a sketch
- step one : do this (master bias by combining biases ?)
- step two : then do that (master dark by combining darks ?)
- step three : do this ( Look at the flats and find the trimsec and biasec).

For the moment i need to return to the iraf old docmentation to understand the sequence of the tasks to perform.

Many thanks for your help.

Sylvie

**Comment by sylvielsstfr** [comment]
OK, I have seen your jupyter notebook here

http://nbviewer.jupyter.org/gist/mwcraig/06060d789cc298bbb08e

I probably have to do something with  the biassec and trimsec to the biases before combining them into a master bias file.
Now I understand better how to proceed.

For the darks, I had series of swept Exposure. I will keep these exposure inside a numpy array indexed by the file number.

I will adapt your jupyter notebooks to my needs.

Best Regards.

Sylvie

**Comment by crawfordsm** [comment]
Thanks Sylvie -- let us know if you have any questions although I think that notebook may be a little out of date. The master dark can be created using the `combine` task and then subtracted using the `subtract_dark`  scaling by the exposure time.   

However, overscan and master bias subtraction should be done before that step.

**Comment by mwcraig** [comment]
Closing...
