### ISSUE TITLE
Adding 'median' function

### ISSUE THREAD

**Issue by AlexaVillaume** [astropy/ccdproc#371]
This is a continuation of what was discussed in issue #370.

I'm going to try to recreate the IRAF task 'median'. I imagine it as essentially being a wrapper to the scipy medfilt2 function.

I'm new to contributing so any suggestions about how best to proceed are welcome!

**Comment by mirca** [comment]
Hi @AlexaVillaume,

if you haven't contributed to astropy before, you might want to take a look at [How to make a code contribution ](http://docs.astropy.org/en/stable/development/workflow/development_workflow.html).

Best =)

**Comment by crawfordsm** [comment]
A median function would be a great place to start and it sounds like like wrapping the scipy function would work well.   If you have any questions or would like any help with the intermediate steps, please feel free to post here about any of the steps.  

For overall development workflow, the link above is a good place to start.   For ccdproc, I'd suggest taking a look at the functions in core.py in ccdproc for examples of how functions should look like or work.   Some ones that might be good to look at are transform_image or rebin.  

Once you have some code, please make a pull request and we will be happy to discuss it and work through the process if needed.

**Comment by mwcraig** [comment]
@AlexaVillaume -- good to hear from you! One other place to look is in `combine.py`. I've never used IRAF so I'm not sure what it's median does, but there are some median options for combining already.

The big thing to make sure you do is to create a git branch to work on before you make changes. That makes it infinitely easier to fix any issues down the road.

**Comment by pllim** [comment]
I think @saraogaz and @justincely would be interested in this as well.
