### ISSUE TITLE
Doctest stumbles upon astropy info message in reduction_toolbox.rst

### ISSUE THREAD

**Issue by olebole** [astropy/ccdproc#373]
When running doctest, I get the following error:
```
_________________ [doctest] docs/ccdproc/reduction_toolbox.rst _________________
164 specifying the overscan and region to be retained in a trim.
165 
166 Overscan subtraction
167 ++++++++++++++++++++
168 
169 To subtract the overscan in our image from a FITS file in which ``NAXIS1=232`` and
170 ``NAXIS2=100``, in which the last 32 columns along ``NAXIS1`` are overscan, use `~ccdproc.subtract_overscan`:
171 
172     >>> # python-style indexing first
173     >>> oscan_subtracted = ccdproc.subtract_overscan(cr_cleaned,
Expected nothing
Got:
    INFO: parent_nddata should be a weakref to an NDData object. [astropy.nddata.nduncertainty]
    INFO: parent_nddata should be a weakref to an NDData object. [astropy.nddata.nduncertainty]

/tmp/ccdproc-test-v5YrZs/docs/ccdproc/reduction_toolbox.rst:173: DocTestFailure
```
IMO, the logging should be switched off before.

**Comment by mwcraig** [comment]
@olebole - I'm having trouble reproducing this...when I run the doctest locally, it passes, and when it runs on CI it also doesn't occur. How  are you running the doctests?

**Comment by MSeifert04** [comment]
@mwcraig This is the warning message for the memory leak. Maybe it should have been some more frightening message (Memory leak) instead of this "weakref" hint.

I suspect that the astropy version is > 1.2 with ccdproc < 1.1. This error does not happen with the current master branch of ccdproc or with astropy < 1.2.

**Comment by mwcraig** [comment]
Closing as it appears to be fixed on master.
