### ISSUE TITLE
Allow ImageFileCollections to take a list

### ISSUE THREAD

**Issue by crawfordsm** [astropy/ccdproc#374]
Instead of giving a directory as the entry to ImageCollections, it should also be able to take a list of images so the user can specify exactly what files they want included.

**Comment by mirca** [comment]
Hi @crawfordsm,

should the files be assumed to be in ``location`` or should it be any list of relative (or absolute) paths?

I was thinking in add a parameter which would be the list of files specified by the user wrt to ``location``, is that the intention?

**Comment by crawfordsm** [comment]
@mirca maybe both?   If location is supplied then an absolute path not needed, but if location is None then it would need an absolute path

**Comment by crawfordsm** [comment]
One part of this has been implement in #403, but different locations still needs to be implemented.

**Comment by mwcraig** [comment]
What if, instead of switching based on image location, we do the Unix-y thing of using an absolute path if the filename starts with `/` but otherwise we use pre-pend location?

**Comment by mwcraig** [comment]
Am leaning towards either a list of paths (allowing both relative and absolute) or dropping...
