### ISSUE TITLE
Will there be a v.1.1.x branch now that 1.1 is released?

### ISSUE THREAD

**Issue by MSeifert04** [astropy/ccdproc#385]
Great job at the new release of ccdproc! :tada: :+1: 

But I've noticed that there is no ``v1.1.x`` branch. I sometimes need to investigate some cross-version issues (especially with astropy 1.2) and having a seperate branch for each major release makes it a bit easier.

**Comment by mwcraig** [comment]
I've created it but haven't pushed it yet... Coming tonight!
