### ISSUE TITLE
Can I set the dtype of the combined image?

### ISSUE THREAD

**Issue by KerryPaterson** [astropy/ccdproc#391]
Hi

I am trying to combine a list of fits files with ccdproc.combine(). Is there a way to set the dtype of the combined image? The data in the fits files are uint16 but I want the combined image to be float32. I tried setting the dtype within ccdproc.combine() but this doesn't seem to work. I tried testing this with a list of CCDData objects as well, but it made no difference. I also tried converting the dtype the other way i.e. use float32 data and try set dtype in ccdproc.combine() to uint16, with no success in setting the dtype.

**Comment by MSeifert04** [comment]
@KerryPaterson Thank you for the report. Am I right that you only want the result in another dtype? Or is some convenience function (clipping?) not behaving correctly on your dtype?

**Comment by MSeifert04** [comment]
You can use `ccdproc.Combiner` directly which accepts a `dtype` parameter.

**Comment by KerryPaterson** [comment]
Yes, I only want the result in another dtype. Using ccdproc.Combiner works. What is the difference between using ccdproc.Combiner vs cddproc.combine? ccdproc.Combiner doesn't seem to like the ccd_list if it does not contain CCDData objects, unlike ccdproc.combine which will accept a list of fits files.

**Comment by MSeifert04** [comment]
> What is the difference between using ccdproc.Combiner vs cddproc.combine?

simplified: ``combine`` is a convenience function so one doesn't need to read in the files manually, then uses `Combiner` (optionally with clipping) and then just returns the result.

**Comment by KerryPaterson** [comment]
Should passing an argument (for example dtype) in combine not then carry through to Combiner?

**Comment by MSeifert04** [comment]
Unfortunatly not. Currently there is no way to pass it to the `Combiner` but I'm working on a PR enabling it.

**Comment by MSeifert04** [comment]
@KerryPaterson I've submitted a PR to fix this issue. I think (or hope) it will be fixed in the next `ccdproc`-release.

**Comment by KerryPaterson** [comment]
@MSeifert04 Thanks for the help.

**Comment by crawfordsm** [comment]
Okay this should be now merged.
