### ISSUE TITLE
MemoryError combining fits files

### ISSUE THREAD

**Issue by dokeeffe** [astropy/ccdproc#396]
I'm trying to combine many bias frames with ccdproc.combine and get 'MemoryError'
Its about 50 bias frames, each one 16Mb. 
Is this a problem in my code or ccdproc?
My machine has 4GB ram, I just tried passing mem_limit=1e9 to the combiner but get the same result

```
INFO: Splitting each image into %d chunks to limit memory usage to %d bytes. [ccdproc.combiner]
INFO:astropy:Splitting each image into 1 chunks to limit memory usage to 16000000000 bytes.
WARNING: VerifyWarning: Keyword name 'trim_image' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created. [astropy.io.fits.card]
WARNING:astropy:VerifyWarning: Keyword name 'trim_image' is greater than 8 characters or contains characters not allowed by the FITS standard; a HIERARCH card will be created.
Traceback (most recent call last):
  File "masterBiasGenerator.py", line 36, in <module>
    generate_master_bias_frames()
  File "masterBiasGenerator.py", line 29, in generate_master_bias_frames
    calibrationUtils.combine_values_from_dictionary_and_write(raw_bias_frames, 'master_bias', combine_method)
  File "/home/dokeeffe/Code/github/bh-observatory/data-reduction/calibration/calibrationUtils.py", line 73, in combine_values_from_dictionary_and_write
    master = ccdproc.combine(v, method=combination_method)
  File "/home/dokeeffe/.local/lib/python2.7/site-packages/ccdproc/combiner.py", line 571, in combine
    comb_tile = getattr(tile_combiner, combine_function)()
  File "/home/dokeeffe/.local/lib/python2.7/site-packages/ccdproc/combiner.py", line 358, in average_combine
    data, wei = scale_func(scalings * self.data_arr,
  File "/usr/lib/python2.7/dist-packages/numpy/ma/core.py", line 3947, in __rmul__
    return multiply(other, self)
  File "/usr/lib/python2.7/dist-packages/numpy/ma/core.py", line 966, in __call__
    result = self.f(da, db, *args, **kwargs)
MemoryError
```

**Comment by mwcraig** [comment]
@dokeeffe -- what version of ccdproc are you using? My initial reaction is that combine should work for your case. Does it still fails if you set `mem_limit` even lower?

**Comment by MSeifert04** [comment]
@dokeeffe I hope you don't mind that I've added triple quotes around your error (multiline-code-block) so it's better readable.

Thank you for the report and that could well be some numpy-error. Could you share the data you were processing and the script (including the scale-function, etc.) and your numpy version?

**Comment by dokeeffe** [comment]
Yes I set it even smaller (128e6) and its processing
```
INFO: Splitting each image into %d chunks to limit memory usage to %d bytes. [ccdproc.combiner]
INFO:astropy:Splitting each image into 7 chunks to limit memory usage to 128000000 bytes.
```

I'm using ccdproc 
Version: 1.0.1
Also....
Name: numpy
Version: 1.11.0

The code I'm using is a script I have written and is here...
https://github.com/dokeeffe/bh-observatory/tree/master/data-reduction/calibration
Called masterBiasGenerator.py

**Comment by dokeeffe** [comment]
Maybe I should close this issue, sorry for wasting your time and thanks for the help!

**Comment by MSeifert04** [comment]
@dokeeffe So it was just a problem with the memory limit?

**Comment by dokeeffe** [comment]
Yes setting to 128mb seemed to do the trick. Thanks for the help

**Comment by MSeifert04** [comment]
I recently fixed a problem where the memory calculation was way off (it thought it was dealing with uint8 when internally float64 was used). Maybe that also affected your use-case.

But I'm glad it worked.

**Comment by mwcraig** [comment]
@dokeeffe -- I'm glad to hear that worked (and always happy to hear that people are using the code!)
