### ISSUE TITLE
ccd_process does not keep header

### ISSUE THREAD

**Issue by crawfordsm** [astropy/ccdproc#401]
When ccd_process processes a file, the return object appears to lose its header information.

**Comment by MSeifert04** [comment]
This might just one or several of the functions called by `ccd_process`. For example:

```
>>> ccd = ccdproc.CCDData(np.ones((4, 4)), unit='adu', meta={'a': 1})
>>> ccdproc.ccd_process(ccd).meta
{'a': 1, 'ccd_process': 'ccd=<CCDData>'}
```
is no problem.

Do you know how (which keywords) you invoked `ccd_process`?

**Comment by RogueAstro** [comment]
After running PyCharm's debugger, I inspected the ``CCDData`` object that is returned after a ``ccd_process`` call, and there is only one entry in its header: 

    'ccd_process' (4364907760) = {str} 'dark_frame=None, ccd=<CCDData>, gain=1.0 electron / adu, trim=None, master_bias=<CCDData>'`

The original header was completely lost.

**Comment by MSeifert04** [comment]
@RogueAstro Am I right that you just provided `ccd`, `gain` and a `master_bias` when you called `ccd_process`? 

On a personal note: I'm somewhat surprised by this `(4364907760) = {str}` thing.

**Comment by RogueAstro** [comment]
Yes, that is true. As for ``(4364907760) = {str}``, it may just be some metadata that PyCharm prints when we inspect an object. The striking fact is that the header contains only one entry, and it is this long string ``'dark_frame=None, ccd=<CCDData>, gain=1.0 electron / adu, trim=None, master_bias=<CCDData>'``. I would expect it to preserve the header from the input ``ccd``, and/or to just append this ``ccd_process`` entry to the original header.
