### ISSUE TITLE
Should there be docs for block_* functionality?

### ISSUE THREAD

**Issue by SaraOgaz** [astropy/ccdproc#406]
Hi guys,

I saw the added functions in  #402 and was wondering if there were plans to add this to the docs, I can't seem to find a reference to it when I poke around....

**Comment by mwcraig** [comment]
Yes, there should be -- thanks for catching that!

**Comment by MSeifert04** [comment]
That's weird. There could be circumstances (astropy < 1.1) when the documentation for these functions is not built but that should not be the case with the RTD docs.

When I build it locally there is documentation. Maybe it's just some RTD caching issue. @mwcraig @crawfordsm could you clear (sometimes it needs 3-4 clears) and rebuild the docs?

**Comment by MSeifert04** [comment]
It looks like this locally (I hope there is not some weird sphinx stuff going on):

![unbenannt](https://cloud.githubusercontent.com/assets/14200878/19536201/405b9582-964b-11e6-9599-2ee3040082e5.jpg)

![unbenannt1](https://cloud.githubusercontent.com/assets/14200878/19536246/6be70696-964b-11e6-8089-3c1ca85934b8.jpg)

**Comment by MSeifert04** [comment]
Ok, sorry for the flood of comments but somehow the RTD build stalled lately: http://readthedocs.org/projects/ccdproc/builds/

Maybe because I added scikit-image to the dependencies? Does this affect the RTD builds?

**Comment by mwcraig** [comment]
Looks like this is closed by #407 -- now the sphinx documentation at least include `block_*` in the API section.

@SaraOgaz -- can you please confirm that and close if appropriate? (arguably we should still add something to the *narrative* documentation about this too...)

**Comment by SaraOgaz** [comment]
Yep I see it, thanks! Closing...
