### ISSUE TITLE
combine fails with StdDevUncertainty?

### ISSUE THREAD

**Issue by joshwalawender** [astropy/ccdproc#424]
It looks like `combine` fails for images with a `StdDevUncertainty`.  I'm working on a simple reduction and am trying to carry uncertainty though the whole process.  While writing the bias file combine step, I got an error which I can reproduce below:

```
import ccdproc
import numpy as np
import astropy.units as u
from astropy.nddata import StdDevUncertainty

readnoise = ccdproc.Keyword('RDNOISE', unit=u.electron)
readnoise.value = 10.
bias_images = []
for i in range(3):
    bias_image = ccdproc.CCDData(np.ones((16,16), dtype=int)*1000, unit='adu')
    bias_image.uncertainty = StdDevUncertainty(np.ones(bias_image.data.shape) * readnoise.value)
    bias_images.append(bias_image)
    
master_bias = ccdproc.combine(bias_images)
```

Yields:

```
Traceback (most recent call last):
  File "quicktest.py", line 22, in <module>
    master_bias = ccdproc.combine(bias_images)
  File "/Users/vysosuser/git/ccdproc/ccdproc/combiner.py", line 585, in combine
    size_of_an_img += ccd.uncertainty.nbytes
AttributeError: 'StdDevUncertainty' object has no attribute 'nbytes'
```

Am I using uncertainty correctly or should I be doing this differently?

---

Don't forget to include the version of astropy, ccdproc and numpy, just copy
this into your Python interpreter (without the backticks):

```
>>> import astropy
>>> print(astropy.__version__)
1.0.4
>>> import ccdproc
>>> print(ccdproc.__version__)
1.2.dev967
>>> import numpy
>>> print(numpy.__version__)
1.9.3
```

**Comment by MSeifert04** [comment]
@joshwalawender Thank you for the report. 

I had a similar issue and I think I fixed it in #416 but just to be on the safe side, could you checkout the PR and see if it fixes your issue?

**Comment by joshwalawender** [comment]
@MSeifert04 It looks like your #416 fixes the problem.  Closing this as a duplicate.

**Comment by MSeifert04** [comment]
@joshwalawender Thanks!
