### ISSUE TITLE
Duplicate build on AppVeyor

### ISSUE THREAD

**Issue by astrofrog** [astropy/ccdproc#439]
It looks like there are two ccdproc builds in the Astropy organization on AppVeyor:

https://ci.appveyor.com/project/Astropy/ccdproc
https://ci.appveyor.com/project/Astropy/ccdproc-iqpau

Is there a reason for this? Can we remove the empty one and rename the other one to not have the iqpau suffix?

**Comment by mwcraig** [comment]
@astrofrog - I have no idea how that happened....

@MSeifert04 -- yes, I think.

**Comment by mwcraig** [comment]
There were two webhooks to appveyor which is what (I suspect) led to the duplicates. The one called https://ci.appveyor.com/project/Astropy/ccdproc-iqpau is the one that is actually working, and ist still around.

I've deleted the other in appveyor and removed the inactive webhook from this repo.
