### ISSUE TITLE
PEP8 travis check

### ISSUE THREAD

**Issue by MSeifert04** [astropy/ccdproc#446]
Would it be worthwhile to enable the `pycodestyle` (PEP8) Travis job? Like [the one in astropy.](https://github.com/astropy/astropy/blob/master/.travis.yml#L105)?

**Comment by bsipocz** [comment]
It depends how many new contributors you have. I think it's rather useful if most of the commits are coming from the core team (and also having a bit more strict list of errors you check for, core astropy only checks for a very few trivial ones), but it can also be a burden and raises the bar if you have many git/github newbie, see comment here: https://github.com/astropy/astropy/pull/4581#issuecomment-184942922

E.g. in astroquery we run it with allow to fail, but would be nice to move it out from there at some point.

**Comment by MSeifert04** [comment]
True anough with the higher bar for new contributors. But one can specify which are actually tested? 

So we might find a set that just tests the more important ones like: trailing whitespaces, no newline EOF, blank line with whitespaces?

**Comment by bsipocz** [comment]
Yes, that's what astropy core does.

**Comment by crawfordsm** [comment]
So yes on a very limited set of tests

**Comment by bsipocz** [comment]
I've just revised my stand on this and moved the pycodestyle test out of the allowed failures in astroquery. Leaving it there just resulted in getting a messier code over time. With github now allowing maintainers to push directly to PR branches, we can easily help our new contributors when/if they are stuck due to the style errors.

**Comment by MSeifert04** [comment]
@bsipocz Could you have a look at #478 and check if what I did there is correct? I'm always suspicious if I need to change travis.yml in non-trivial ways.
