### ISSUE TITLE
[1.10] Failure with numpy 1.12 (rc)

### ISSUE THREAD

**Issue by olebole** [astropy/ccdproc#448]
With numpy 1.12 (resp. 1.12RC), the `test_wcs_project_onto_scale_wcs` fails at least with Python 2.7:

```
ccd_data = CCDData([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
   ....,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
           1.,  1.,  1.,  1.,  1.]])

    @pytest.mark.data_size(31)
    def test_wcs_project_onto_scale_wcs(ccd_data):
[...]
        # Define a cutout from the new array that should match the old.
        new_lower_bound = (np.array(new_ccd.shape) -
                           np.array(ccd_data.shape)) / 2
        new_upper_bound = (np.array(new_ccd.shape) +
                           np.array(ccd_data.shape)) / 2
        data_cutout = new_ccd.data[new_lower_bound[0]:new_upper_bound[0],                                 new_lower_bound[1]:new_upper_bound[1]]
E       TypeError: slice indices must be integers or None or have an __index__ method

ccdproc/tests/test_ccdproc.py:817: TypeError
```
Full build log [here](http://aws-logs.debian.net/2016/12/19/ccdproc_1.1.0-1_unstable.log). Corresponding Debian bug [here](https://bugs.debian.org/848812).

**Comment by MSeifert04** [comment]
@olebole This should be fixed in `ccdproc 1.2` (released last week).

I encountered and fixed that problem in #417.

Is there any reason not to use version 1.2 (note that it got an additional dependency: `scikit-image`) there?

**Comment by olebole** [comment]
skimage currently has some problems in Debian, and I am not sure whether they are solved in the next weeks (we have a freeze for the upcoming Stretch release soon). Until the skimage package is in a good shape, I prefer not to update ccdproc, but to backport the patch.

**Comment by MSeifert04** [comment]
Do you need us to do anything? As far as I know we don't do backports and/or bugfix releases (cc: @astropy/ccdproc-maintainers, maybe I'm wrong).

**Comment by olebole** [comment]
No; I did the backport [myself](https://anonscm.debian.org/cgit/debian-astro/packages/ccdproc.git/tree/debian/patches/fixed-numpy-dev-test-failure.patch). The build time test was successfull, and now I am going to upload to Debian.

**Comment by MSeifert04** [comment]
👍 Thanks!
