### ISSUE TITLE
Try harder to correctly handle WCS with SIP distortion

### ISSUE THREAD

**Issue by mwcraig** [astropy/ccdproc#457]
The way that SIP distortions in a WCS are handled changed in astropy 1.2 when converting a WCS to a header. See https://github.com/astropy/astropy/pull/4814 for details.

In particular, if a WCS has been created with SIP distortion coefficients *and* the `CTYPE` contains `SIP` then the `SIP` is dropped from the CTYPE when converting the WCS back to a header using `to_header` *unless* `relax=True` in the call to `to_header`.  See extensive discussion at the PR above and in the issues linked to from the PR for motivation.

Suppose you have an image the SIP distortion in the WCS, then do these steps:

```python
# Read the image...
img = CCDData.read('m101-007b.fit')
img.write('i-have-no-sip.fit')
```

you will get this warning:
```
WARNING: Some non-standard WCS keywords were excluded: BP_0_0, BP_0_1, BP_0_2, B_1_1, B_2_0, A_ORDER, B_0_2, B_ORDER, BP_ORDER, AP_ORDER, A_1_1, BP_2_0, AP_2_0, A_0_2, BP_1_1, BP_1_0, A_2_0, AP_1_0, AP_1_1, AP_0_1, AP_0_0, AP_0_2 Use the ``relax`` kwarg to control this. [astropy.wcs.wcs]
```

I think the desired outcome is to keep the distortion keywords if `SIP` is in `CTYPE`...i.e. the simple fix is to use `relax=True` in `to_header`.

In fact, the final image will, when read back in, will still apply SIP distortions because the distortions are never removed from the header (when we convert the WCS `to_header` we do not delete any WCS-related keywords already in the header).

**Comment by janga1997** [comment]
@mwcraig Could I have that FITS file referenced to in the description?
