### ISSUE TITLE
Test suite of ImageFileCollection uses non-existing header keywords

### ISSUE THREAD

**Issue by MSeifert04** [astropy/ccdproc#468]
While fixing #461 I noticed that the exceptions came because the keywords passed to the file collection and the ones present in the fits-file-headers differ. That lead to a number of subtle bugs (and a lot of warnings when manually executing them).

Maybe the tests (including those in the narrative documentation) should be updated to use actual present header pairs. It wouldn't hurt to have some testing what happens when non-existing keywords are requested but the majoritiy of the test suite shouldn't depend on it.

**Comment by MSeifert04** [comment]
Update: The `image-management`-doctests are currently skipped because of this.

**Comment by janga1997** [comment]
@MSeifert04 Is this issue fixed? I've definitely clicked on it ten times, realizing every time you already made a PR.

**Comment by MSeifert04** [comment]
@janga1997 No it's not fixed. However it's quite an amount of work because changing tests is tricky. One has to assert for each affected test seperatly what it is doing. Sometimes it's easy because the test name is really descriptive and/or there is a comment in the test what is tested. Then after changing it one has to make sure the test is still testing the correct issue and covers the same code paths.

It's not hard but it takes time.

**Comment by mwcraig** [comment]
Seems like we ought to fix this or abandon it....
