### ISSUE TITLE
Add keywords.deleter for ImageFileCollection

### ISSUE THREAD

**Issue by MSeifert04** [astropy/ccdproc#470]
Currently the summary of a ImageFileCollection can be wiped by setting the keywords to None, however using `del xxx.keywords` fails because there is no deleter assigned to the property.

I think it would be a good idea to have that deleter for the keywords (and maybe deprecate the option to wipe the keywords by setting `xxx.keywords = None`, I mean it's also possible to almost wipe them when one uses `xxx.keywords = []`).

Also currently the `keywords.setter` has a default value of `None` for the `keywords` which makes no sense (except one accesses the `__class__.keywords.fset`-method directly).

**Comment by janga1997** [comment]
@MSeifert04 I would like to take this up too.

**Comment by MSeifert04** [comment]
@janga1997 That would be great!

FYI: you don't need to ask for permission, if you feel confident that you can provide the feature and you have time to manage another PR then just go ahead and make a pull request.

**Comment by janga1997** [comment]
@MSeifert04 If we set `XXX.keywords = []`, `XXX.keywords` yields `['file']` instead of wiping them.

**Comment by MSeifert04** [comment]
@janga1997 Yes, that's why I said _almost_.

**Comment by janga1997** [comment]
@MSeifert04 Could you help out with that merge problems in the other PR?
