### ISSUE TITLE
Representation for ImageFileCollection

### ISSUE THREAD

**Issue by MSeifert04** [astropy/ccdproc#471]
Currently `ImageFileCollection` lacks a `__repr__` method. However I'm not exactly sure what the representation should contain. Maybe just the directory, the number of files and the keywords (basically the inputs) or the whole `summary`?

**Comment by janga1997** [comment]
@MSeifert04 I would like to take this up.

> Maybe just the directory, the number of files and the keywords (basically the inputs) or the whole summary

Is that it, or do you have any more additions?

**Comment by MSeifert04** [comment]
@janga1997 That's the difficult part here, I don't know. :)

**Comment by janga1997** [comment]
@MSeifert04 I think just printing the parameters on init should be fine. Because while we have a way to get the summary, we don't a way to currently print the parameters of initialization.

**Comment by mwcraig** [comment]
I think going the with input is fine. That would be:

+ location
+ keywords passed in on initialization (I don't remember whether this is currently stored in the class, so a hidden attribute might need to be added to store it).
+ `filenames`, if that was not `None` when the object was created.
+ `info_file`, if that was not `None` when the object was created.

**Comment by mwcraig** [comment]
Closed by #475
