### ISSUE TITLE
Add examples to  ImageFileCollection docstrings

### ISSUE THREAD

**Issue by bsipocz** [astropy/ccdproc#479]
There is no example section in the docstring of ImageFileCollection.hdus while there is reference to it. Even without the reference I think it would be very valuable to have basic examples for methods/functions in this package.

```
In [14]: image_coll.hdus?

``overwrite`` evaluates to ``True`` the generator will write a copy of
each FITS file it is iterating over. In other words, if
``save_with_name`` and/or ``save_location`` is a string with non-zero
length, and/or ``overwrite`` is ``True``, a copy of each FITS file will
be made.

Parameters
----------
save_with_name : str, optional

...
kwd :
    Any additional keywords are used to filter the items returned; see
    Examples for details.

```

**Comment by MSeifert04** [comment]
I think this refers to the `files_filtered` docstring (which contains some examples). This would be fixed by the doc-changes in #539.
