### ISSUE TITLE
methods of ImageFileCollection should accept multiple values for a keyword

### ISSUE THREAD

**Issue by bsipocz** [astropy/ccdproc#480]
I was unable to find a way to filter out hdus in a one liner that has the object name as either “FLAT” or “DOME”. If would be rather nice to be able to specify a given keyword twice, or give a list or similar to it. 

My current workaround is rather ugly:

```
from ccdproc import ImageFileCollection
import itertools

image_coll = ImageFileCollection('rawdir')
fl = image_coll.hdus(return_fname=True, object='FLAT’)
do = image_coll.hdus(return_fname=True, object=‘DOME’)
flats = itertools.chain(fl, do)
```

**Comment by bsipocz** [comment]
A somewhat  related feature request is to have a way to use formal logic for the keyword value matching. E.g. have a generator for everything that is not a bias, or not 2x2 binning, etc.

(if you prefer to have singe requests per issues I can open another one).

**Comment by SaraOgaz** [comment]
If i'm understanding this correctly and can add to this request, it would be great to use <, > with some of the keyword values, i.e.  exptime > 300.

**Comment by mwcraig** [comment]
I would really like to get input from @duckrojo on this and ideally perhaps incorporate some of dataproc here 😀.
