### ISSUE TITLE
ImageFileCollection's methods to accept multiple word keywords

### ISSUE THREAD

**Issue by bsipocz** [astropy/ccdproc#481]
Most of the data in ESO produced headers are stored in HIERARCH keywords with multiple words. Currently it’s not possible to provide these nicely as keywords for methods of ImageCollection. 

My current workaround is to provide a dict with the keyword requirements and unpacking it at method call:

```
hdu, fname = image_coll.hdus(return_fname=True, **{'cdelt1':1, 'ESO TPL ID':'EFOSC_spec_obs_Spectrum’})
```

It would be nice to have be able to provide this dict directly via a keyword (e.g. kwd_dict=None), or mentioned this in the docs.

**Comment by MSeifert04** [comment]
That's definetly annoying. But if one has to create the dictionary anyhow then a new parameter would be just a convenience to omit the unpacking (`**`). Also having a `kwd_dict` besides `kwd` and `ccd_kwargs` as parameters makes a function signature really confusing.

But it should be documented, I wonder where [the promised Examples](https://github.com/astropy/ccdproc/blob/master/ccdproc/image_collection.py#L692) are...
