### ISSUE TITLE
Set up astrobot to remind us about changelog entries and milestones

### ISSUE THREAD

**Issue by mwcraig** [astropy/ccdproc#489]
We should use astrobot to check that PRs have a changelog and have been milestoned, as suggested by @bsipocz in #488.

**Comment by MSeifert04** [comment]
How would we do that anyway? It probably requires some changes in the package settings and does the bot need instructions or is it based on fixed rules?

**Comment by bsipocz** [comment]
The bot is a github app that you need to authenticate for each repo (to be more precise, I think it needs to be an org admin who authenticate it). It is static in the sense that you cannot customize it at the moment.

https://github.com/astropy/astropy-bot

**Comment by mwcraig** [comment]
Closing, because I think this is done...

**Comment by MSeifert04** [comment]
It is?

**Comment by mwcraig** [comment]
I pushed a button last not that I thought turned it on but haven’t checked the PR I opened last night.

**Comment by mwcraig** [comment]
Nope, it did not run. Will investigate
