### ISSUE TITLE
Why do we need unit conversion to bias/flat before doing ccd_process?

### ISSUE THREAD

**Issue by ysBach** [astropy/ccdproc#490]
I have asked this to the "Python users in Astronomy" group page of FB and M. Durant and M. Craig kindly suggested me to open an issue here.

`ccdproc.ccd_process` takes the `master_bias` and `master_flat` in the unit of "after gain correction", which usually means "electron" unit. But the bias/flat I have is in ADU, which is usually the case, and of course the input image (`CCDData` object) is in ADU too.

What I learnt from M. Craig's answer is that I have to multiply gain (`gain=2.1 * u.electron/u.adu`) to bias and flat but NOT to the object image, before plugging those in to `ccd_process`:

```python
bias = CCDData.read('../bias/bias.fits', unit='adu')
obj  = CCDData.read('obj.fits', unit='adu')
reduced = ccd_process(obj, master_bias=bias) # This works correctly
reduced = ccd_process(obj, master_bias=bias,  # This gives error
                      gain=2.1*u.electron/u.adu, 
                      readnoise=11*u.electron))
```

But the second one gives following error:
```
UnitConversionError: Can only apply 'subtract' function to quantities with compatible dimensions
```

For me this seems quite strange that I have to multiply gain to the bias and flat before plugging them in to `ccd_process`. It is clear that it should multiply gain to get electron unit if the unit of bias is in adu. Is there any specific reason for this, i.e., why do we have to multiply gain to bias/flat before using them?

This happens when I plug "gain" factor into the ccd_process.

Thanks in advance :)

**Comment by crawfordsm** [comment]
We do have the gain correction prior to the master bias subtraction step.   So, to subtract a master bias it must be in the same units as your gain correct image.   Currently, there are three steps that you can do:

1.  As @mwcraig suggested, you can gain correct your current master bias frames.

2.  When you process your bias frames, you can apply the gain correction to them as well.

3.  You can run the steps individual on your frames and in your preferred order.

I'd be open to switching the order or adding something that would check what has been done on the bias frame and applying it in the right order.   Let me know if you have a preferred order or would prefer something else.  `ccd_process` is there as a convenience function so hopefully it should be convenient and useful!   We just haven't gotten a lot of feedback on it, so anything helps.

**Comment by ysBach** [comment]
Thanks for the reply :)

What I prefer is this: 
I want `ccd_process` to be able to accept bias, flat, and object as ADU.

I can imagine like this: 
`ccd_process` has an option like `gain_corrected=True` as default for backward compatibility.
If we put `gain_corrected=False`, then `ccd_process` understands that it has input of bias and flat in the unit of "before gain correction", not "after gain correction". 
As far as I know, `gain_corrected=False` may be used only when we want to calculate the errormap and get the output in unit of electron, not in ADU. 
So if `gain_corrected=False`, the input `gain` will be multiplied to the input `master_bias` and `master_flat`, etc, and `readnoise` will be used to make an errormap for the given `CCDData`.

Plus, something like `output_format="electron"` which can at least also take `"adu"`, can tune the output result's unit.
