### ISSUE TITLE
ccdproc.combine input as numpy array

### ISSUE THREAD

**Issue by ysBach** [astropy/ccdproc#493]
[`ccdproc.combine`](http://ccdproc.readthedocs.io/en/stable/api/ccdproc.combine.html#ccdproc.combine) currently accepts `list` or `str`, not `numpy.ndarray`.

I guess it is also quite common to have the filename as `numpy.ndarray` format, e.g., if I read a file named "file.list" using `numpy.loadtxt`. 

So I want to ask whether there's any reason for accepting only `list` or `str`, not `numpy.ndarray`.

**Comment by MSeifert04** [comment]
There are lots of unsupported formats: `numpy.loadtext`, `hdf5`, ...

`combine` is actually just a convenience function that supports FITS files and `CCDData` objects. It's likely noone had a use-case for `numpy.loadtxt` yet. If you don't need the chunked processing you can easily just pass in a list of `CCDData`:

```
filenames = [...]
ccds = [CCDData(np.loadtext(filename, ...)) for filename in filenames)
combine(ccds, ...)
```

**Comment by crawfordsm** [comment]
@ysBach I have no objection to including it.  I'd encourage you to contribute it, and if you need any help, just let us know.

**Comment by mwcraig** [comment]
Remilestoned, since we now have a PR to address this...thanks, @ysBach!
