### ISSUE TITLE
Python 3.6 compatibility

### ISSUE THREAD

**Issue by elmichelangelo** [astropy/ccdproc#494]
I want to install ccdproc and get the following error

```
PS C:\Windows\system32> conda install -c astropy ccdproc
Fetching package metadata .............
Solving package specifications: .


UnsatisfiableError: The following specifications were found to be in conflict:
  - ccdproc -> python 2.7*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```
astropy version: 1.3.2  np122py36_0
numpy version: 1.12.1 py36_0

**Comment by MSeifert04** [comment]
Ah thanks for spotting that. `ccdproc` is python 3.6 compatible but it's missing the builds for conda for python 3.6.

@mwcraig is there some package conflict?

**Comment by bsipocz** [comment]
@MSeifert04 - There were some missing dependencies at the time, but now everything should be OK and the conda packages should be available in about an hour.

**Comment by MSeifert04** [comment]
@bsipocz Great, thank you!

**Comment by elmichelangelo** [comment]
Thanks!
