### ISSUE TITLE
Image Combine - sum

### ISSUE THREAD

**Issue by ysBach** [astropy/ccdproc#500]
Sometimes it is easier to combine the images as "sum", not just average/median combine.
Although this can sometimes be achieved by multiplying the number of images to the average combined image, it is not possible if many images have different sizes, etc.

So I want to suggest to implement an attribute to `Combiner`, such as `sum_combine`.

**Comment by mwcraig** [comment]
@ysBach thanks for this and your suggestion in #499...and congrats for being the one to open our 500th issue! 🎉

**Comment by MSeifert04** [comment]
Thanks for reporting this. Just a question about the expected behaviour: Should it return the pure sum or the scaled sum? I'm asking because we allow masked arrays.

For example should: `[1, 1, -, 1, 1]` return `4` or `5` (the `-` represents a masked value)?

**Comment by ysBach** [comment]
@MSeifert04 

Sorry for this delayed reply.

> For example should: `[1, 1, -, 1, 1]` return `4` or `5` (the - represents a masked value)?

I guess `[1, 1, -, 1, 1]` means the pixel values of 5 different ccds at the same location given to the `Combiner` (and the third ccd has `mask` value of `True` at the given location). 

Then I think `4` is the reasonable choice. A person would have given 5 masked arrays because it is better to ignore certain pixel value(s). And I also guess that is the way how average/median combine works if masked array is given (isn't it?). If the user wanted `5` as the result of the "sum combination", I think the input images would have been non-masked ones.

**Comment by MSeifert04** [comment]
The average and median ignore masked pixels completly, so if `[1, 1, -, 1, 1]` is given then it's summed (4) and divided by the number of valid pixels (4) and gives 1. If the masked pixel is not ignored the number of pixels would be 5 and the result `0.8`. 

I would define a `sum`-combine just as a `average`-combine that is multiplied by the number of images. So it would return `5`.

But that's always a problem with masked arrays, it's not immediatly obvious how masked pixels should behave. Should they be ignored? Should they be treated as zero?

**Comment by hletrd** [comment]
Implemented as pure sum in #508. (as imcombine in IRAF)
