### ISSUE TITLE
Dropping support for astropy 1.0 (LTS)?

### ISSUE THREAD

**Issue by MSeifert04** [astropy/ccdproc#504]
In a few days/weeks astropy 2.0 will be released. It's labelled the "next" LTS and the support (bug fixes, etc.) for 1.0 (the current LTS) will be dropped.

Will `ccdproc` drop support for the astropy 1.0 LTS when 2.0 is released? If so, will there be another release before 1.0 support is dropped? If not, how long will `ccdproc` (roughly) support the 1.0 LTS?

**Comment by mwcraig** [comment]
I'd lean towards dropping 1.x some reasonable amount of time (a month? maybe two?) after 2.0 is out. I'm thinking a new release by the end of the summer would make sense.

**Comment by crawfordsm** [comment]
When we make our next release, we will make sure it works with 1.0, but then drop testing on the 1.0 branch after release.

**Comment by bsipocz** [comment]
As astropy 2.0 is release, the LTS from the point of view of ci-helpers is 2.0. If you want to keep testing against the 1.0 branch, you need to specify the version number in your travis file.

**Comment by MSeifert04** [comment]
closed in favor of #511
