### ISSUE TITLE
ccdproc not in macports

### ISSUE THREAD

**Issue by iskreng** [astropy/ccdproc#514]
Hi,

it seems that ccdproc is not available port in macports. Is there any plan to port it?

Cheers,
Iskren

**Comment by mwcraig** [comment]
It would be great if it were ported, but none of the ccdproc maintainers uses mac ports. One potential hangup would be ccdproc's dependencies (e.g. astroscrappy, reproject) that are also not on macports...

**Comment by Russell-Jones-OxPhys** [comment]
We've been looking at this, and are doing local testing. A new release of ccdproc with a recent astropy_helpers (as in the master branch) would be helpful.

**Comment by mwcraig** [comment]
We are hopefully not more than a week or so from a release.....

**Comment by Russell-Jones-OxPhys** [comment]
:(

**Comment by mwcraig** [comment]
@Russell-Jones-OxPhys - good news, @MSeifert04 uploaded v1.3.0 to PyPI a little while ago. Sorry for the extended delay!

**Comment by Russell-Jones-OxPhys** [comment]
@mwcraig @MSeifert04 Thanks :+1:  I've drafted portfiles which seem to build OK and will file a trac.macports.org ticket, hopefully tomorrow.

**Comment by MSeifert04** [comment]
@Russell-Jones-OxPhys Just FYI: There had been some problems for Debian with 1.3.0 of ccdproc (#589 ) which is why we released 1.3.0.post1 recently.

But more interesting: Is ccdproc now available in macports?

**Comment by Russell-Jones-OxPhys** [comment]
Not yet, I'm afraid. C colleague got it working by other means, so it dropped down the priority list. I'm hoping to get back to it soonish.

**Comment by mwcraig** [comment]
Closing, but if there are things we can do for 2.0 that would make macports packaging easier, let us know.

**Comment by iskreng** [comment]
Thanks for looking at this guys. And no worries. I have now completely migrated to conda.
