### ISSUE TITLE
Make the glob attributes for ImageFileCollection readonly?

### ISSUE THREAD

**Issue by MSeifert04** [astropy/ccdproc#516]
The `ImageFileCollection` has `glob_include` and `glob_exclude`. These are currently settable but they only take effect if one `refreshs` the instance. The `location`, `files` and `ext` attributes are readonly because they also would take effect only when refreshed.

Should the `glob_include/exclude` also be readonly?

**Comment by crawfordsm** [comment]
Yes, they should be readonly.
