### ISSUE TITLE
Indexing Convention?

### ISSUE THREAD

**Issue by jvntra** [astropy/ccdproc#555]
Have had issues with indexing conventions using ccdproc, namely with the use of `overscan_subtract` and `trim_image`. It'd be helpful to have further clarity on indexing using different tools in the documentation.

**Comment by crawfordsm** [comment]
When you have time, can you give some more details about what you'd like to see more of?    Otherwise, we'll try to update the part of the docs with index information with more details.  Thanks for commenting!

**Comment by MSeifert04** [comment]
I think it always follows the normal Python/NumPy style but I have been using Python for so long, I probably just don't know what "newcomer" problems might be.

If you could give some examples of "unexpected" or "intuitive" behaviors that would be very welcome. 👍

**Comment by mwcraig** [comment]
Changing milestone since we need more information....

**Comment by mwcraig** [comment]
Closing, but please reopen if you are able to provide more details.
