### ISSUE TITLE
Documentation notes

### ISSUE THREAD

**Issue by crawfordsm** [astropy/ccdproc#556]
Here are some documentation  notes/areas that could use improvement:

- the reduction tool box is given as a series of tasks but it might be useful to organize it so it is more of a tutorial
- our users may not be coming from a numpy/python background so expanding on ideas or proving better links to concepts like indices, pass by referencing, and masking may be helpful
- in README add links to indicate other places that might be useful to ask questions like stackoverflow, python and astronomy facebook group, and astropy mailing list.
- Add link to numfocus for donations

**Comment by MSeifert04** [comment]
I recently added the `ccdproc` tag to StackOverflow. I don't know if that's useful but it could be a good address for people trying to find help wrt to `ccdproc` that don't fit the astropy-mailing list or such like.

**Comment by mwcraig** [comment]
I'm wondering if this can be closed given https://github.com/mwcraig/ccd-reduction-and-photometry-guide
