### ISSUE TITLE
question about uncertainty in combiner

### ISSUE THREAD

**Issue by SaraOgaz** [astropy/ccdproc#562]
Hi,

I'm trying to follow the logic here for the combining of uncertainty and I'm getting a bit confused.  It looks like the standard deviation is getting taken twice? Once when the original uncertainty array gets made and again when it calls ``StdDevUncertainty(uncertainty)``?  Also, it looks like there's no way to change the call to ``StdDevUncertainty``?

https://github.com/astropy/ccdproc/blob/b6e85f6887d777683ed045ad39fc86745217a698/ccdproc/combiner.py#L433

**Comment by MSeifert04** [comment]
It only creates one array, the `StdDevUncertainty(uncertainty)` just wraps the array because `CCDData` expects an `NDUncertainty` instance - not a plain array. 

But you're right: Currently there's no uncertainty except `StdDevUncertainty`.

**Comment by SaraOgaz** [comment]
Would you guys be against me putting in a PR to have combiners take a provided uncertainty array and add a quadrature calculation to spit out the final uncertainty.  This (with weighting) is what imcombine is doing by default I believe.  It looks like right now combining won't use the input uncertainty arrays for anything right now, it just gets fed the std generated one?

**Comment by SaraOgaz** [comment]
I should add, I have gotten a request for a Python equivalent of this from several people at STScI.

**Comment by MSeifert04** [comment]
> Would you guys be against me putting in a PR to have combiners take a provided uncertainty array and add a quadrature calculation to spit out the final uncertainty.

We always welcome PRs!

I was thinking about having `VarianceUncertainty` besides `StddevUncertainty` but in almost all cases it's easy enough to just use `.uncertainty.array ** 2` to get the variance so I never bothered much about the formal addition of `VarianceUncertainty`. :)

**Comment by crawfordsm** [comment]
Definitely would welcome it!

**Comment by MSeifert04** [comment]
>  It looks like right now combining won't use the input uncertainty arrays for anything right now, it just gets fed the std generated one?

I missed that one: Yes that's correct.

**Comment by SaraOgaz** [comment]
Will do, gonna start on it today.
