### ISSUE TITLE
flat_correct: allow passing in a normalization factor

### ISSUE THREAD

**Issue by bjweiner** [astropy/ccdproc#577]
flat_correct automatically calculates the mean of the flat field and normalizes the flat before dividing by it. This is convenient, but if you want to use two different flats on different sets of images but force them to have the same normalization, there is no way to turn off the normalization or pass in an externally determined factor.

This becomes an issue when processing multi-extension FITS files. For example, if extensions 1 and 2 are two different CCDs, or two halves of the same CCD, and one tries to process them by running flat_correct on the two extensions separately, then the flats need to have the same normalization. (Imagine that the left half of the CCD is extension 1 and it is 10% more sensitive than ext 2. Then both the science targets and the flat field will have 10% more counts in ext 1, and the target should be divided down by the brighter flat field. Renormalizing ext 1 and ext 2 separately by their own means will produce a non-flat science image.)

For an example of how I had to work around this behavior, you can see the function _renormalize_by_flat()_ in the pipeline [here](https://github.com/bjweiner/ARTN/blob/master/mont4k_pipeline/kuiper_reduce.py#L509). It would be simpler just to have a normalizing factor passed in as an optional argument to ccdproc.flat_correct. I can write this code and issue a pull request, but someone with more practice will need to read it for style and write a test.

This is a small part of making ccdproc friendly to multi-extension FITS files, but can stand on its own.

**Comment by MSeifert04** [comment]
Thanks for opening this issue! I've edited your post so the link works, just in case you're wondering what had been edited.

I'm a bit hazy on multi-CCD or multi-ADC CCDs reduction steps but if it would help you if you can pass in the normalization as argument that would be fine with me. 👍

**Comment by crawfordsm** [comment]
I might be working on a similar problem shortly so I'd definitely be open to making the normalization as a potential variable.   If you have time for a PR, it would be very welcome.   Happy to work with you to help with style and testing.
