### ISSUE TITLE
Do a 1.3 release?

### ISSUE THREAD

**Issue by eteq** [astropy/ccdproc#586]
I wonder if it may be time to do a new release?  I see the last one was at the end of 2016, and I've now twice gotten people who are trying to use astropy v2.0 with ccdproc and running into `CCDData` issues (i.e., the problem that #528 fixes), so even just that fix is probably worth of a new release.

Are there other items that are "almost" done that a release is waiting on, or can one just be cut nowish?

cc @mwcraig @crawfordsm @MSeifert04

**Comment by mwcraig** [comment]
Actually, it is way past time for a new release 😕 ...current plan is to get it out tomorrow....

**Comment by MSeifert04** [comment]
1.3.0 should be available on PyPI, it will take a bit until they are available on conda-forge (and the astropy channel).
