### ISSUE TITLE
Only zipfile on pypi

### ISSUE THREAD

**Issue by olebole** [astropy/ccdproc#589]
Hi,

for the Debian package, I (automatically) download the ccdproc package from PyPI. 1.3.0 has, however, only a zip file (MS-DOS line endings) there, which is a bit unfortune for packaging purposes (Patches etc.).

Would you consider to upload a tar.gz as well there? Or should I switch to the github release of ccdproc (would be OK for me as well)?

**Comment by MSeifert04** [comment]
It was my mistake that I did upload the zip with ms-dos encodings. 😓 
Unfortunately we cannot upload further source files after the PyPI release. However, we can release a `tar.gz` as 1.3.1 if it causes problems.

cc @astropy/ccdproc-maintainers

**Comment by olebole** [comment]
I didn't test; however I use other Python packages directly from github, so the problems are solvable. I would however prefer Pypi, since this is where everyone gets the package.
Probably a 1.3.1 on pypi would be preferrable; also since others may have problems with a zipfile there.

**Comment by bsipocz** [comment]
@MSeifert04 - you don't necessarily need to do a 1.3.1, doing a post release would be enough in this case I think.

**Comment by MSeifert04** [comment]
I totally lost track of this. So a post-release would essentially be a release with a version number of `1.3.0.post1`?

I'll try to use my linux VM to do the upload then which should take care of the `zip` and `CLRF` line-endings.

**Comment by mwcraig** [comment]
That is correct -- I think the way to do it would be to tag the `1.3.0.post1` release on the 1.3 branch

**Comment by MSeifert04** [comment]
Okay, I just released the `1.3.0.post1` version. It should be a `tar.gz` without windows-line-endings.

**Comment by MSeifert04** [comment]
Unfortunately our CI is failing for this post-release (but these also fail for master and the original 1.3.0 release). 😓

**Comment by mwcraig** [comment]
So far you are having what is, in my experience, a perfectly normal release cycle 😮 😀

**Comment by mwcraig** [comment]
Once @olebole can confirm that `post1` works for him I think we can close this issue and work on the failing tests separately.

**Comment by olebole** [comment]
Yes, this works well. I just uploaded the new version to Debian. Thank you very much!

**Comment by MSeifert04** [comment]
Thanks @olebole for raising this issue and for uploading it to Debian!

I'm closing this issue now but if other problems arise feel free to open a new issue :)
