### ISSUE TITLE
Unicode characters in setup.cfg causing problems

### ISSUE THREAD

**Issue by jankansky** [astropy/ccdproc#590]
Failure of
python ./setup.py install

with error:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1372: ordinal not in range(128)

It seems that some unicode single quotes are causing problems in the setup.cfg file.  By making the following change, I was able to build and install ccdproc:
```
diff --git a/setup.cfg b/setup.cfg
index b10ce38..6ad8697 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -44,7 +44,7 @@ github_project = astropy/ccdproc
 # E224 - tab after operator
 # E225 - missing whitespace around operator
 # E241 - multiple whitespace after ','
-# E242 - tab after <E2><80><98>,<E2><80><99>
+# E242 - tab after ','
 # E251 - unexpected spaces around keyword / parameter equals
 # E271 - multiple spaces after keyword
 # E272 - multiple spaces before keyword
```

**Comment by crawfordsm** [comment]
Thanks  -- I'm having a little trouble reproducing it.   Can you let me know the version of python you are using and are you doing this from the current development version of ccdproc?

**Comment by MSeifert04** [comment]
I assume this is a Windows problem with Python 3.6 (that changed quite some things with regard to character encoding). Would be good if that could be confirmed.

However, there's absolutely no reason not to change the quotations, so if you like to make a PR that would be great. :)

**Comment by jankansky** [comment]
Ubuntu 16.04.2 LTS 
python 3.6

Here is a way to trigger it:
conda create -n py36test python=3.6 ipykernel
source activate py36test
conda install notebook ipykernel
ipython kernel install --user
git clone https://github.com/astropy/ccdproc.git
cd ccdproc
python ./setup.py install

Error reading setup.cfg: UnicodeDecodeError(....
