### ISSUE TITLE
Doctests and NumPy

### ISSUE THREAD

**Issue by MSeifert04** [astropy/ccdproc#593]
NumPy changed a lot of representations (ndarray, ma.MaskedArray) lately and these broke and still break our doctests. Even if we make them work it's not garantueed that it won't happen again and in several cases the doctest examples suffer from the "fixes" by being slightly inaccurate (the `# doctest: +FLOAT_CMP` does more than just compare for "rough equality") or by deliberately removing part of the output (when using `# doctest: +ELLIPSIS`).

I'm at a loss what should be done, personally I would like to run the doctests only if the installed NumPy is the latest released NumPy. That still requires some work when a new NumPy version is released but we don't have to support multiple NumPy versions in the documentations. However that way we don't get any notifications (test failures) for the tests against NumPy-dev...

Another option would be: Skipping the doctests and "re-implementing" them as ordinary tests. But that has the disadvantage that we need to keep them in sync and we effectively don't get any notifications if the representation changes.

This is just to throw some ideas around, I don't plan to implement/test any of them soon.

**Comment by crawfordsm** [comment]
Failing doc tests are annoying -- I'd probably lean towards picking a version and sticking with that version of numpy until we no longer support it or there is a good reason to move to the next version.   That might lower the load a little bit of having to update everything every time numpy releases.   On the other hand, it might mean there is a big update when we do shift to the next version of numpy

**Comment by bsipocz** [comment]
I would advise against turning of the doctest in the hope of keeping them in sync with the tests. That just simply never worked out well before. Probably the solution is to not run them for the numpt-dev tests only.

**Comment by MSeifert04** [comment]
I have been looking quite a bit now but I haven't found any switches to enable/disable doc-tests on a per test-setup basis. That makes it quite a bit harder to run the doctests only on specific NumPy versions. That would've been my favorite as well...

**Comment by MSeifert04** [comment]
@bsipocz I know but crippling/obfuscating doctests so they pass the CI isn't good either. In the best case they just look weird/odd but in the worst case they become useless because the need to support different NumPy versions makes the "result" inaccurate.

**Comment by mwcraig** [comment]
Closing because we think this was fixed, but please reopen if not.
