### ISSUE TITLE
Wildcard support for ImageFileCollection.files_filtered

### ISSUE THREAD

**Issue by SaOgaz** [astropy/ccdproc#595]
Hi,

I'm hoping to use ImageFileCollections in my STAK IRAF translation notebooks to replace hselect, but I've run into a few missing features.  I see there's an '*' option for the `files_filtered` method, but it's not very useful when you can't combine the asterick with other characters, i.e.

`collection.files_filtered(filter='*F*')`

Any chance this could be added?

**Comment by MSeifert04** [comment]
Not a dupe but related: #480. 

I think that would be a great addition but I'm not sure how easy it will be to implement it. 🤔

**Comment by SaraOgaz** [comment]
Might be worth looking at how header objects do it, I know it can natively take an arguement with a wildcard.  Probably regex stuff...

**Comment by MSeifert04** [comment]
No, `ImageFileCollection` doesn't support wildcards, not for keywords and not for values.

The problem with keywords is that it becomes ambiguous if the wildcards match more than 1. What should be the result if one value associated with a keyword-with-wildcard matches the filter and another one doesn't?

For values it would be more straightforward, just a matter of implementing wildcard-matching (which isn't easy but not too hard either).
