### ISSUE TITLE
files_filtered question (ImageFileCollection)

### ISSUE THREAD

**Issue by SaOgaz** [astropy/ccdproc#596]
Tangentially related to #595, the way I see most people use hselect is to return the `table` style output after filtering by some keyword values.  I can't see from the documentation, is there an easy way to take the return list of filenames from `files_filtered` and return an updated table based on that filter? It seems like if I were going to use built in `Table` methods to do this I would have the user skip straight to filtering the first table return, and not use `files_filtered` at all.  But maybe this was the intention all along?

I guess what I'm really asking is, are there plans to write a table_filtered method, and if not, what's the reasoning to having a 'files_filtered' and not a `table_filtered'?  Just thinking out loud here, apologies if these seems overly critical.

**Comment by MSeifert04** [comment]
I was thinking about making a `filter` that just returns a filtered ImageFileCollection with filtered `summary`, but I haven't got the time yet. I'll see if I can add that soon-ish.

**Comment by mwcraig** [comment]
The interesting thing is that the table is filtered, sort of. `files_filtered` and the generators (`.hdus` and friends) set a mask on the `file` column to do their work. Will try something quick to see if I can make summary reflect that.

If so I might add a "clear filters" or "clear masks" method to reset.

**Comment by mwcraig** [comment]
Decision is to implement a `filter` method that uses the new initialize-from-list feature in #680
