### ISSUE TITLE
Type of ImageFileCollection summary property

### ISSUE THREAD

**Issue by MSeifert04** [astropy/ccdproc#601]
Currently it can be a `Table` or `None` (no files) or an empty list (no keywords). Internally it's also temporarily (shouldn't be visible to users) set to an empty dictionary. However the docs state that it's a Table.

Personally I would prefer if it would always be a `Table`, however that would be backwards-incompatible, especially for checks regarding `if collection.summary` tests (Tables are always True).

Does it make any sense to change the behavior here?

**Comment by mwcraig** [comment]
How about this:

+ No keywords returns a table with one column (files)
+ No files returns `None` (could be talked into a table of length zero instead)

**Comment by mwcraig** [comment]
Will implement as above
