### ISSUE TITLE
Fix more numpy dev doctest failures (plus one real doctest fail)

### ISSUE THREAD

**Issue by mwcraig** [astropy/ccdproc#605]
This build has a few fails: https://travis-ci.org/astropy/ccdproc/jobs/316795322

Most look like whitespace changes in numpy `repr` but one appears to be a genuine fails.

**Comment by MSeifert04** [comment]
I'll have a look at these failures.

**Comment by MSeifert04** [comment]
The latest Cron didn't fail (https://travis-ci.org/astropy/ccdproc/builds/322810515) so we can probably close this issue?
