### ISSUE TITLE
ImageFileCollections: Fits file without .fits

### ISSUE THREAD

**Issue by crawfordsm** [astropy/ccdproc#620]
If there isn't a '.fits' extension on a file, `ImageFileCollections` will not pick up the file.   The ability to select files without that extension would be a helpful enhancement.

**Comment by mwcraig** [comment]
@crawfordsm -- did you have in mind checking for a wider range of extensions ('.fit', '.fits', '/fts', ...) or checking each file to see if it is FITS? IIRC, the latter is possible and there may even be a function in astropy for it...

**Comment by crawfordsm** [comment]
The use case was a fits file without a proper extension.  So, I think it
would be the former case.  It would be useful to explicitly pass it the
files that you want to use

>

**Comment by mwcraig** [comment]
If file is given (list of files) it should use those.

**Comment by mwcraig** [comment]
Could do this by modifying the init to allow for a "check file contents for fits" flag, trying an implementation...
