### ISSUE TITLE
Fitting models with rejection

### ISSUE THREAD

**Issue by crawfordsm** [astropy/ccdproc#63]
Fitting models with rejecting points is a need for the ccdproc package, for example in fitting the overscan region.    However, this is probably something that astropy.modeling will eventually take care of, but in the meantime, we should supply something.

**Comment by MSeifert04** [comment]
That was recently added to astropy if I'm correct: https://github.com/astropy/astropy/pull/4760

**Comment by mwcraig** [comment]
Closing, as this proposed to provide the functionality now in astropy core.
