### ISSUE TITLE
Request: Passing 1D array of weights to average_combine

### ISSUE THREAD

**Issue by stevans** [astropy/ccdproc#634]
The default scaling function for average_combine (numpy.ma.average) can take a list of weights, but average_combine requires the weights to be 2D arrays. Can average_combined be changed to allow 1D arrays of weights?

Here's a link to the numpy.ma.average doc for convenience: https://docs.scipy.org/doc/numpy/reference/generated/numpy.ma.average.html

-Matt

**Comment by kakirastern** [comment]
Hi @crawfordsm, has anyone been assigned the issue, and if so is this issue resolvable by someone with lesser experience like me? I am interested in working on it in preparation for GSoC 2019 but am not sure.

**Comment by hlabathems** [comment]
Following numpy.ma.average as a guide, I don't know if changing weights function to something like below would work?

` def weights(self, value, axis = 0):
        if value is not None:
            if isinstance(value, np.ndarray):
                if value.shape != self.data_arr.data.shape:
                	if value.ndim != 1:
                		raise ValueError("1D weights expected when shapes of the data and weights differ.")
                	if value.shape[0] != a.shape[axis]:
                		raise ValueError("Length of weights not compatible with specified axis.")

                self._weights = (np.broadcast_to(value, (self.data_arr.data.ndim-1)*(1,) + value.shape).swapaxes(-1, axis)
                    
            else:
                raise TypeError("weights must be a numpy.ndarray.")
        else:
            self._weights = None`

**Comment by hlabathems** [comment]
Following numpy.ma.average as a guide, I don't know if changing weights function to something like below would work?

` def weights(self, value, axis = 0):
        if value is not None:
            if isinstance(value, np.ndarray):
                if value.shape != self.data_arr.data.shape:
                	if value.ndim != 1:
                		raise ValueError("1D weights expected when shapes of the data and weights differ.")
                	if value.shape[0] != a.shape[axis]:
                		raise ValueError("Length of weights not compatible with specified axis.")

                self._weights = (np.broadcast_to(value, (self.data_arr.data.ndim-1)*(1,) + value.shape).swapaxes(-1, axis)
                    
            else:
                raise TypeError("weights must be a numpy.ndarray.")
        else:
            self._weights = None`

**Comment by hlabathems** [comment]
Following numpy.ma.average as a guide, I don't know if changing weights function to something like below would work?

`def weights(self, value, axis = 0):
        if value is not None:
            if isinstance(value, np.ndarray):
                if value.shape != self.data_arr.data.shape:
                	if value.ndim != 1:
                		raise ValueError("1D weights expected when shapes of the data and weights differ.")
                	if value.shape[0] != a.shape[axis]:
                		raise ValueError("Length of weights not compatible with specified axis.")
                self._weights = (np.broadcast_to(value, (self.data_arr.data.ndim-1)*(1,) + value.shape).swapaxes(-1, axis)       
            else:
                raise TypeError("weights must be a numpy.ndarray.")
        else:
            self._weights = None`

**Comment by hlabathems** [comment]
Following numpy.ma.average as a guide, I don't know if changing weights function to the following would work?

`def weights(self, value, axis = 0):
    if value is not None:
        if isinstance(value, np.ndarray):
            if value.shape != self.data_arr.data.shape:
                if value.ndim != 1:
                    raise ValueError("1D weights expected when shapes of the data and weights differ.")
                    if value.shape[0] != a.shape[axis]:
                        raise ValueError("Length of weights not compatible with specified axis.")
            self._weights = (np.broadcast_to(value, (self.data_arr.data.ndim-1)*(1,) + value.shape).swapaxes(-1, axis)
        else:
            raise TypeError("weights must be a numpy.ndarray.")
    else:
        self._weights = None`

**Comment by hlabathems** [comment]
Following numpy.ma.average as a guide, I don't know if changing weights function to the following would work?

def weights(self, value, axis = 0):
    if value is not None:
        if isinstance(value, np.ndarray):
            if value.shape != self.data_arr.data.shape:
                if value.ndim != 1:
                    raise ValueError("1D weights expected when shapes of the data and weights differ.")
                    if value.shape[0] != a.shape[axis]:
                        raise ValueError("Length of weights not compatible with specified axis.")
            self._weights = (np.broadcast_to(value, (self.data_arr.data.ndim-1)*(1,) + value.shape).swapaxes(-1, axis)
        else:
            raise TypeError("weights must be a numpy.ndarray.")
    else:
        self._weights = None

**Comment by hlabathems** [comment]
Following numpy.ma.average as a guide, I don't know if changing weights function to something like below would work?

` def weights(self, value, axis = 0):
    if value is not None:
        if isinstance(value, np.ndarray):
            if value.shape != self.data_arr.data.shape:
                if value.ndim != 1:
                    raise ValueError("1D weights expected when shapes of the data and weights differ.")
                    if value.shape[0] != a.shape[axis]:
                        raise ValueError("Length of weights not compatible with specified axis.")
            self._weights = (np.broadcast_to(value, (self.data_arr.data.ndim-1)*(1,) + value.shape).swapaxes(-1, axis)
        else:
            raise TypeError("weights must be a numpy.ndarray.")
    else:
        self._weights = None `

**Comment by hlabathems** [comment]
<def weights(self, value, axis = 0):
    if value is not None:
        if isinstance(value, np.ndarray):
            if value.shape != self.data_arr.data.shape:
                if value.ndim != 1:
                    raise ValueError("1D weights expected when shapes of the data and weights differ.")
                    if value.shape[0] != a.shape[axis]:
                        raise ValueError("Length of weights not compatible with specified axis.")
            self._weights = (np.broadcast_to(value, (self.data_arr.data.ndim-1)*(1,) + value.shape).swapaxes(-1, axis)
        else:
            raise TypeError("weights must be a numpy.ndarray.")
    else:
        self._weights = None>

**Comment by hlabathems** [comment]
Following numpy.ma.average as a guide, I don't know if changing weights function to the following would work

```
def weights(self, value, axis = 0):
    if value is not None:
        if isinstance(value, np.ndarray):
            if value.shape != self.data_arr.data.shape:
                if value.ndim != 1:
                    raise ValueError("1D weights expected when shapes of the data and weights differ.")
                    if value.shape[0] != a.shape[axis]:
                        raise ValueError("Length of weights not compatible with specified axis.")
            self._weights = (np.broadcast_to(value, (self.data_arr.data.ndim-1)*(1,) + value.shape).swapaxes(-1, axis)
        else:
            raise TypeError("weights must be a numpy.ndarray.")
    else:
        self._weights = None
```
