### ISSUE TITLE
License section is plural.

### ISSUE THREAD

**Issue by simontorres** [astropy/ccdproc#635]
License section of RTD says **Licenses**. Is this intended? or it is a typo?

**Comment by bsipocz** [comment]
Accidental, I suppose when that part was copied over, the template dealt with multiple ones (just like we have multiple ones in astropy).
PRs are welcome ;)

**Comment by simontorres** [comment]
I see, I was wondering if it was possible to do have more than one license in one project. I'll do the PR.

**Comment by bsipocz** [comment]
Hmm, I would ping @pllim, but while I'm not a lawyer, I suspect one can have multiple compatible licences, or different ones for different parts of the code?

**Comment by pllim** [comment]
I am no lawyer either, but the uses of "licenses" is not unprecedented. Astropy core uses it -- https://github.com/astropy/astropy/tree/master/licenses

**Comment by pllim** [comment]
@eteq is more well-versed at software licensing than me.

**Comment by mwcraig** [comment]
Fixed by #636
