### ISSUE TITLE
Removal of deprecated astropy.tests.pytest_plugins from conftest.py L9

### ISSUE THREAD

**Issue by kakirastern** [astropy/ccdproc#660]
Hi,

My recent commits in PR #659 passed almost all the tests that should be have been passed except for the Travis CI. Upon closer inspection of the code, I found out that there is some problem with the following file: 

[https://github.com/astropy/ccdproc/blob/master/ccdproc/conftest.py](https://github.com/astropy/ccdproc/blob/master/ccdproc/conftest.py)

The error thrown in the output of the Travis CI is as follows:

```
ImportError while loading conftest '/tmp/ccdproc-test-r9jki1ep/lib/python3.6/site-packages/ccdproc/conftest.py'.
ccdproc/conftest.py:9: in <module>
    from astropy.tests.pytest_plugins import *
E   ModuleNotFoundError: No module named 'astropy.tests.pytest_plugins'
The command "$MAIN_CMD $SETUP_CMD" exited with 4.
```

([https://travis-ci.org/astropy/ccdproc/jobs/493581671](https://travis-ci.org/astropy/ccdproc/jobs/493581671))

Is there anything I can do about the situation? 

I think this Issue is related to astropy/astropy#7782...

**Comment by mwcraig** [comment]
Yeah, that dates back to when the pytest plugins were part of astropy itself as opposed to being in a separate package like they are now. Will devote some time on Friday to ccdproc, which really needs some TLC...

**Comment by kakirastern** [comment]
Yeah, and I should work on restructuring the docs soon to help with improving the flow, now that I know more about how best to fix/reorganize its contents and where to find info to help me with the task.

**Comment by mwcraig** [comment]
Even a suggested outline for updated documentation would be very helpful....a full re-write is a pretty heavy lift!

**Comment by kakirastern** [comment]
Yup, you are right... Will go through the docs again and come up with some suggestions

**Comment by mwcraig** [comment]
I'm going to fix this one as part of finishing up #650

**Comment by kakirastern** [comment]
Okay, sure

**Comment by MatteoSerafino** [comment]
Hi everybody, 
I'm still trying to figure out how to fix the problem.
I'm new in GitHub, so I do not know exactly how to move.
May you help me?
what should I change??
