### ISSUE TITLE
Creating an ImageFileCollection with filenames set will create an empty collection

### ISSUE THREAD

**Issue by york-stsci** [astropy/ccdproc#661]
If I create a list of FITS files, and then create an ImageFileCollection with filenames set to that list, the created collection ends up being empty. For example,

    my_files = glob.glob("/path/to/directory/*.fits")
    my_collection = ImageFileCollection(filenames=my_files)

the resulting collection is empty. However, if I instead do:

    my_files = glob.glob("/path/to/directory/*.fits")
    my_collection = ImageFileCollection(filenames=my_files, location="something_completely_random")

then I get a collection made up of everything in filenames (as long as location is not None). Looking at the __init__ function, it seems that it only checks the value of `filenames` if `location` isn't None. Shouldn't it check `filenames` for a list of files regardless?

**Comment by mwcraig** [comment]
Thanks for reporting this @york-stsci -- I haven't used image file collections this way myself (explicit list of file names) so getting a report about the behavior is useful.

**Comment by hlabathems** [comment]
@york-stsci I followed your first example without specifying the location and when I do print(my_collection), the resulting my_collection is non-empty, my_collection is a list of files in my_files. Is this the behavior you were expecting?

**Comment by crawfordsm** [comment]
Looking at this in a little more detail, the `filename` attribute is still populated, but when, for example, looking at `my_collection.summary` is empty when `filename` is populated but `location` is None
