### ISSUE TITLE
ImageFileCollection summary has type unicode for every keyword

### ISSUE THREAD

**Issue by york-stsci** [astropy/ccdproc#662]
If an ImageFileCollection is created from a number of FITS files, it will have a summary table containing information on all of the keywords. If you look for the keyword types, every keyword is listed as being type unicode string regardless of the type of the keyword in the original FITS header.

**Comment by mwcraig** [comment]
Again, thanks for reporting -- can this be reproduced with the same code you provided in #661?

**Comment by york-stsci** [comment]
Yes, it can be. Or, at least, I found it with the same file collection that I was using when I found that issue.
