### ISSUE TITLE
Attempts to install ccdproc via conda trigger Python 3.6 reversion

### ISSUE THREAD

**Issue by JuanCab** [astropy/ccdproc#667]
If I attempt

conda -c astropy ccdproc

in a conda environment with python 3.7 installed, when it goes through the dependency check, it reverse all the packages to their python 3.6 versions.  Maybe one of the dependencies hasn't been moved to python 3.7? (I have astropy 3.1.2 and numpy 1.16.4 installed in addition to python 3.7.3.

**Comment by crawfordsm** [comment]
Unfortunately, I'm not able to reproduce this currently.   

Can you currently reproduce this?   If so, can you also share your OS ?

This could be possible solved by the recent updates and releases.

**Comment by JuanCab** [comment]
It’s been fixed by Matt Craig.  I suspect this issue didn’t get closed yet.  I’ll close it.
