### ISSUE TITLE
running python setup.py develop fails on macOS Mojave version 10.14.2

### ISSUE THREAD

**Issue by hlabathems** [astropy/ccdproc#669]
This is the template for bug reports, if you have a feature request or question
you can safely ignore and delete this prefilled text.

Include a description of the problem: What are you trying to do (include your
code and the **full** traceback)? What did you expect?

```
Include a minimal example to reproduce the issue including output and
traceback. The triple backticks make github render this as a multi-line code
block.
```

Don't forget to include the version of astropy, ccdproc and numpy, just copy
this into your Python interpreter (without the backticks):

```
import astropy
print(astropy.__version__)
import ccdproc
print(ccdproc.__version__)
import numpy
print(numpy.__version__)
```

**Comment by hlabathems** [comment]
After git cloning ccdproc and changing into it, running

python setup.py develop

produces the following

"/usr/local/lib/gcc/x86_64-apple-darwin15.0.0/5.3.0/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1"

And the following command fixes it 

sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /

**Comment by mwcraig** [comment]
Thanks for reporting this -- I *really* wish Apple didn't decide to move around header packages like this!
