### ISSUE TITLE
Misleading error message in subtract_dark

### ISSUE THREAD

**Issue by LionelGarcia** [astropy/ccdproc#674]
#### Issue
In `ccdproc.subtract_dark`, when `scale=False`, error message is misleading when [ValueError is raised](https://github.com/astropy/ccdproc/blob/master/ccdproc/core.py#L662-L674)

#### Example 
```python
# CCDData with different shapes
np.shape(im) # (100, 100)
np.shape(dark) # (90, 90)
im_sub_dark = ccdproc.subtract_dark(im, dark, scale=False)
```
will raise
```
astropy.units.core.UnitsError: Unit 'adu' of the uncalibrated image does not match unit 'adu' of the calibration image
```
Here the error message does not translate the error

#### Versions
- astropy: 3.2.1
- ccdproc: 1.3.0.post1
- numpy: 1.17.0rc1

**Comment by mwcraig** [comment]
Thanks for the bug report @LionelGarcia, will take a look later today.
