### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by mwcraig** [astropy/ccdproc#689]
This is a reminder to do the release some time this week. @MSeifert04 -- the hope is to close the remaining 2.0.0 issues in the next day or so and release some time during pyastro. The big push for 2.1 will be a new combiner interface (while still keeping the old) and performance improvements.

**Comment by mwcraig** [comment]
One thing that will hopefully make it into 2.0 that isn't here yet is using dask to do the array chunking in combiner. @nmiles2718 made great progress towards this at SciPy a couple weeks ago. It looks like it will bring some speedup and can replace the chunking code we currently have in the `combine` function.

**Comment by MSeifert04** [comment]
Thanks for the heads up. I've seen that you fixed a lot of issues already. :+1:

**Comment by MSeifert04** [comment]
2.0.0 is out now, so I'm closing this
