### ISSUE TITLE
Problem in version 2.0.0

### ISSUE THREAD

**Issue by simontorres** [astropy/ccdproc#699]
# Summary

In my opinion a production package do not need to install all development tools. Or from another angle in test code you import from your source file but never in the other direction and this is happening in `image_collection.py`
**References here are from master branch**

https://github.com/astropy/ccdproc/blob/14c22184c69068a684fa271610a9af2a090c696b/ccdproc/image_collection.py#L21

And 

https://github.com/astropy/ccdproc/blob/14c22184c69068a684fa271610a9af2a090c696b/ccdproc/image_collection.py#L1006-L1014

The problem here is that this will require pytest. We are working with containerized applications were you want to be as minimalist as possible. 

Another option is that `pytest` should be in the included as a dependency. (installed automatically upon calling `pip install ccdproc==2.0.0`. However I would like to insist that importing from `test` is wrong.

```
Traceback (most recent call last):
  File "SQM.py", line 21, in <module>
    from goodman_focus.goodman_focus import GoodmanFocus
  File "/usr/local/lib/python3.7/site-packages/goodman_focus/goodman_focus.py", line 13, in <module>
    from ccdproc import CCDData
  File "/usr/local/lib/python3.7/site-packages/ccdproc/__init__.py", line 19, in <module>
    from .image_collection import *
  File "/usr/local/lib/python3.7/site-packages/ccdproc/image_collection.py", line 21, in <module>
    from .tests.pytest_fixtures import directory_for_testing
  File "/usr/local/lib/python3.7/site-packages/ccdproc/tests/pytest_fixtures.py", line 10, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```
My `install_requires` variable contains the following.

```
astropy>=3.2.1
matplotlib>=3.1.0
numpy>=1.16.4
pandas>=0.24.2
scipy>=1.3.0
ccdproc>=1.3.0.post1
sphinx>=2.1.2
```

**Comment by MSeifert04** [comment]
Thank you for the report. I agree that we shouldn't have test-dependencies in the production code.

**Comment by mwcraig** [comment]
Yeah, it turns out this is why all of our doc builds https://aka.ms/win32-x64-user-stable breaking too. I can fix it in about 2 hours....

**Comment by mwcraig** [comment]
@simontorres -- 2.0.1 is on pypi and fixes this issue. Thanks for pointing it out!

**Comment by simontorres** [comment]
Awesome! Thanks @mwcraig
