### ISSUE TITLE
Logo truncated

### ISSUE THREAD

**Issue by astrofrog** [astropy/ccdproc#703]
The logo in the docs is truncated on the right:

<img src="https://ccdproc.readthedocs.io/en/latest/_static/ccdproc_banner.svg">

**Comment by astrofrog** [comment]
I love the square logo on the left though! :+1:

**Comment by mwcraig** [comment]
It may just be because I'm tired, but I'm not seeing what is truncated...we  got the square logo on the left idea from photutils 😀

**Comment by astrofrog** [comment]
Wait what it's not truncated on my laptop... I'll send a screenshot of what it looks like on my desktop shortly.

**Comment by astrofrog** [comment]
I think the rendering of the font is quite dependent on platform/browser - for example on Windows with Edge and Firefox:

![Screenshot (46)](https://user-images.githubusercontent.com/314716/67159461-e9f14000-f33c-11e9-899e-daf8dca2d7c5.png)

I'll try and find the truncated version

**Comment by astrofrog** [comment]
On MacOS X (looks good):

![Uploading Screenshot 2019-10-20 at 13.25.26.png…]()

**Comment by astrofrog** [comment]
On Firefox in Ubuntu 19.04

![Screenshot from 2019-10-20 13-26-33](https://user-images.githubusercontent.com/314716/67159493-481e2300-f33d-11e9-9ab7-8a882ae888a3.png)

**Comment by astrofrog** [comment]
So it looks like a font issue. I wonder if there's a way to save the SVG with the letters as polygons so there's no dependence on fonts?
