### ISSUE TITLE
ccdproc.combine FITS header update

### ISSUE THREAD

**Issue by tapio-not** [astropy/ccdproc#714]
When  using "ccdproc.combine" it would be very useful if the  number of input files would be included to the output file FITS-header, for example like in iraf NCOMBINE=

**Comment by mwcraig** [comment]
Thanks, good suggestion! We'll try to get this done for the next release (which will be fairly soon).

**Comment by mwcraig** [comment]
An other urgent problem came up (#705) that needed fixing, this will get into 2.1.1

**Comment by mwcraig** [comment]
This has been fixed,just need to release it
