### ISSUE TITLE
Change relative imports in tests to absolute imports

### ISSUE THREAD

**Issue by mwcraig** [astropy/ccdproc#735]
Relative imports in tests should be converted to absolute imports. For example, in https://github.com/astropy/ccdproc/blob/master/ccdproc/tests/test_image_collection.py#L22 change `from ..image_collection import ImageFileCollection` to `from ccdproc.image_collection import ImageFileCollection`

If you are working on this please add a comment below saying which test files you are fixing. A small PR that fixes a few is easier to review than a big PR that changes all of them.

**Comment by laserkelvin** [comment]
I can take a crack at this @mwcraig.

**Comment by mwcraig** [comment]
Excellent, thanks!

**Comment by mwcraig** [comment]
This was closed by #737
