### ISSUE TITLE
When tests are run a text file is created in the directory the tests are run in -- that should not happen

### ISSUE THREAD

**Issue by mwcraig** [astropy/ccdproc#736]
When the tests are run a file, `test_table.txt`, is created in the directory in which the tests are run. That is not supposed to happen; it is supposed to go in a temporary directory deleted when the tests finish. The fix might be to stop using the pytest fixture...or there is a bug in the fixture, not sure.

**Comment by laserkelvin** [comment]
I could try and solve this with `tempfile` from the standard lib.

**Comment by laserkelvin** [comment]
@mwcraig I managed to fix this, but my PR for issue [#735] is still open, and I'm not sure if I should create a new PR with the changes?

**Comment by crawfordsm** [comment]
I've reviewed and merged #735, so you should be okay to go ahead and create a new PR

**Comment by mwcraig** [comment]
Closed by #738  -- thanks again @laserkelvin!
