### ISSUE TITLE
CCDproc won't install for Python=3.9 (due to astroscrappy)

### ISSUE THREAD

**Issue by janerigby** [astropy/ccdproc#752]
I was unable to install ccdproc using either conda or pip, for Python=3.9.  For python=3.8 it worked fine.  I don't see such a dependency listed.  

I think I tracked it down to astroscrappy not working with python=3.9.  I'll add an issue there.

**Comment by saimn** [comment]
Ref https://github.com/astropy/astroscrappy/issues/55

**Comment by mwcraig** [comment]
Will try to get a conda build of astroscrappy on Python 3.9 done today....

**Comment by mwcraig** [comment]
Some progress here -- `astroscrappy` can now be installed with conda on python 3.9 -- use either the conda-forge or astropy channel, e.g. `conda install -c conda-forge ccdproc`

**Comment by saimn** [comment]
Version 1.1.0 of astroscrappy is out!

**Comment by mwcraig** [comment]
> Version 1.1.0 of astroscrappy is out!

🚀

Closing this, will update ccdproc shortly to work with the new astroscrappy release.
