### ISSUE TITLE
`Combiner` and `combine` should accept a generator as argument

### ISSUE THREAD

**Issue by mwcraig** [astropy/ccdproc#756]
Both `Combine` and `combiner` should accept a generator (e.g. `Combiner(ifo.ccds())`) instead of requiring that the input be a list (e.g. `Combiner ([ccd for ccd in ifc.ccds()])`). This issue was first raised by @janerigby in #754.

**Comment by Yash-10** [comment]
Hello,

I was wondering whether the implementation of allowing a generator instead of a list of files must take into account the memory usage and speed as an important factor. Of course it would be always better to have the most optimal solution possible but I wanted to know whether this was the motivation for this issue.

Thanks!

**Comment by mwcraig** [comment]
It is mostly intended as a convenience. For `combine` the only way to get the memory chunking is by passing in the file names instead of `CCDData` objects. If the objects are passed in, they will eventually be read into memory even though they are opened by default as memory maps.

At this point `Combiner` essentially requires that the combination fit into memory unless one does their own manual chunking.

**Comment by mwcraig** [comment]
It is just a hassle to have to do things like `[ccd for ccd in ifc.ccds()]` instead of just `ifc.ccds()`. The internals of `Combiner` were written back when we still supported python 2 (which built more around lists than generators) and when generators in python3 behave a little differently. I think some is currently built into `Combiner` at this point that ends up assuming the argument is a list when really the requirement should be a biti less strict: it just needs to be something over which one can iterate.

**Comment by Yash-10** [comment]
Hello @mwcraig, thank you for the explanation! I get it now and will come up with a PR soon.

Thanks!

**Comment by Yash-10** [comment]
Hello @mwcraig, thank you for the explanation! I get it now.

Thanks!
