### ISSUE TITLE
ImageFileCollection filtering and regex_match

### ISSUE THREAD

**Issue by mkelley** [astropy/ccdproc#769]
I'm filtering an ImageFileCollection, trying to find files by filter name.  I've run into a bug with a filter named `'CO+'`.  I use `regex_match=False` to search for the literal filter name, but the code in `ImageFileCollection._find_keywords_by_values` still parses this as a regular expression.  According to the documentation, `regex_match=False` should search by equality.

```python

from tempfile import TemporaryDirectory
import numpy as np
from astropy.io import fits
from ccdproc import ImageFileCollection

h = fits.Header()
h['FILTER'] = 'CO+'

with TemporaryDirectory() as tmpdir:
    fits.writeto(tmpdir + '/test.fits', np.zeros(1), header=h)
    ic = ImageFileCollection(location=tmpdir)

print("filter='CO+'")
print("  regex_match=False", ic.files_filtered(filter='CO+', regex_match=False))
print("  regex_match=True", ic.files_filtered(filter='CO+', regex_match=True))
print()
print(r"filter='CO\+'")
print("  regex_match=False", ic.files_filtered(
    filter=r'CO\+', regex_match=False))
print("  regex_match=True", ic.files_filtered(
    filter=r'CO\+', regex_match=True))
```

The results:

```
filter='CO+'
  regex_match=False []
  regex_match=True ['test.fits']

filter='CO\+'
  regex_match=False ['test.fits']
  regex_match=True ['test.fits']
```

* Filtering with 'CO+' and regex=False should have returned the file, but the result is empty.
* Filtering with 'CO+' and regex=True returns the file, because the regex matches 'CO', as expected.
* Filtering with 'CO\\+' and regex=False should not have returned the file, because the strings are not equal: `'CO+' != r'CO\+'`.
* Filtering with 'CO\\+' and regex=True returns the file, because this regex matches the full string 'CO+'

```
import astropy
print(astropy.__version__)
import ccdproc
print(ccdproc.__version__)
import numpy
print(numpy.__version__)
```
4.0.1.post1
2.1.1
1.18.5

**Comment by mwcraig** [comment]
Closed by #770 -- thanks for reporting this!
