### ISSUE TITLE
Many tests fail with the latest astroscrappy release

### ISSUE THREAD

**Issue by mwcraig** [astropy/ccdproc#777]
For example, `test_cosmicray_gain_correct` fails with:

```
E   TypeError: detect_cosmics() got an unexpected keyword argument 'pssl'
```

**Comment by saimn** [comment]
Oops, yeah several parameters have been renamed. I can have later if you want.

**Comment by mwcraig** [comment]
> Oops, yeah several parameters have been renamed. I can have later if you want.

That would be excellent -- if you can point me some documentation (or commit) that has the renames I do have plenty of time today to work on this.

**Comment by saimn** [comment]
The changes come from https://github.com/astropy/astroscrappy/pull/53, which allow to properly manage the background for spectroscopy. So data should now include the background. And some keywords were renamed for consistency.
