### ISSUE TITLE
ImageFileCollection.hdus returns HDUs not HDULists

### ISSUE THREAD

**Issue by astrofrog** [astropy/ccdproc#792]
The docstring for ``ImageFileCollection.hdus`` mentions that ``HDUList`` objects are returned, but I think this should be ``PrimaryHDU`` or ``ImageHDU`` depending on the ``ext_index``.

**Comment by mwcraig** [comment]
Just to be clear, do you mean that it currently returns an `HDUList` but should return an appropriate `HDU`, or that it returns an `HDU` and should return a list?

**Comment by astrofrog** [comment]
It currently returns HDUs which is fine but the docstring says HDUList
