### ISSUE TITLE
ccdproc 2.4.0 requires astropy 5.0 - Python 3.7 incompatible

### ISSUE THREAD

**Issue by aaronwmorris** [astropy/ccdproc#798]
The latest release of ccdproc 2.4.0 will not run on Python 3.7 due to requiring astropy 5.0 functionality.  astropy 5.0 requires Python 3.8.  The last version of astropy with Python 3.7 compatibility was 4.3.1

Versions
Python: 3.7
ccdproc:  2.4.0
astropy: 4.3.1

```
$ python3.7
Python 3.7.3 (default, Oct 31 2022, 14:04:00)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ccdproc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aaron/git/indi-allsky/virtualenv/indi-allsky/lib/python3.7/site-packages/ccdproc/__init__.py", line 17, in <module>
    from .combiner import *  # noqa
  File "/home/aaron/git/indi-allsky/virtualenv/indi-allsky/lib/python3.7/site-packages/ccdproc/combiner.py", line 53, in <module>
    class Combiner:
  File "/home/aaron/git/indi-allsky/virtualenv/indi-allsky/lib/python3.7/site-packages/ccdproc/combiner.py", line 300, in Combiner
    message='The use_astropy argument has been removed because '
TypeError: deprecated_renamed_argument() got an unexpected keyword argument 'message'
```

The `message` arg for `deprecated_renamed_argument()` was added to astropy 5.0 rc1
https://github.com/astropy/astropy/commit/64edb37137462edd54e5c69432b5ed255c128873

**Comment by mwcraig** [comment]
🤦‍♂️ -- thanks for reporting -- I'll figure out how to proceeed tomorrow, but if you have suggestions (including just bumping the minimum versions) please let me know.

**Comment by aaronwmorris** [comment]
I would agree that bumping the minimum versions is probably the way to go.  Python 3.7 goes end of life in 7 months anyway.

I just think yanking (or updating) the 2.4.0 release from pypi just needs to be done since it incorrectly resolves the dependencies.

**Comment by aaronwmorris** [comment]
Submitted PR #799 .

I did some testing and the minimum astropy version that works without any errors is 5.0.1
