### ISSUE TITLE
new MacBook with current Anaconda, UnsatisfiableError when installing ccdproc

### ISSUE THREAD

**Issue by brianhill** [astropy/ccdproc#815]
I just moved to a new M3 MacBook, and did a completely clean install of Anaconda 2023.09. After cloning base, I did:

`> conda install -c conda-forge ccdproc`

This failed. Complete output ending in the failure follows:

```
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): - WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.9.0.*, but conda is ignoring the .* and treating it as 1.9.0
WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.8.0.*, but conda is ignoring the .* and treating it as 1.8.0
done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                  

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - ccdproc -> python[version='>=3.10,<3.11.0a0|>=3.10,<3.11.0a0|>=3.11,<3.12.0a0|>=3.11,<3.12.0a0|>=3.12,<3.13.0a0|>=3.9,<3.10.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.8,<3.9.0a0|>=3.12.0rc3,<3.13.0a0|>=3.12.0rc3,<3.13.0a0',build=*_cpython]

Your python: defaults/osx-arm64::python==3.11.5=hb885b13_0

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

  - feature:/osx-arm64::__osx==14.2.1=0
  - feature:|@/osx-arm64::__osx==14.2.1=0
  - ccdproc -> numpy[version='>=1.17'] -> __osx[version='>=10.9']

Your installed version is: 14.2.1
```

**Comment by brianhill** [comment]
I have no idea if this was a proper workaround, but since the error messages above seemed to be about the Python version, I downgraded my Python by doing the following,

`> conda install -c anaconda python=3.10`

and then I re-did,

`> conda install -c conda-forge ccdproc`

and my installation completed successfully. My imports from ccdproc,

`from ccdproc import ImageFileCollection, Combiner, combine, subtract_dark, flat_correct`

now work. On to the next dependency!

**Comment by mwcraig** [comment]
Good to hear from you, @brianhill! 

A couple of recommendations regarding anaconda on an ARRM mac (I'm typing on one at the moment):

+ Use miniforge, unless Anaconda (the company) is supplying an ARM-native build (which they might be)
+ Use the conda-forge channel -- it is much more comprehensive than the anaconda or default channel. There are a couple of astro-related packages that still need rebuilds for Python 3.12 but I hope to get those done in the next couple of weeks.
+ Use mamba instead of conda  unless the latest ANaconda distribution already defaults to using libmamba for solving. The mamba solver is much faster and more informative than the old conda solver was.
